@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam class {
  BackgroundColor LightBlue
  BorderColor Blue
}
skinparam enum {
  BackgroundColor LightBlue
  BorderColor Blue
}
hide circle
hide methods

title Domain Model Excerpt: US09 - Buy a Locomotive

class Player {
  username
  password
  initialBudget
  currentBudget
  ownedLocomotives
}

class Scenario {
  nameID
  editor
  startDate
  endDate
  tweakedCityList
  availableIndustryList
  availableLocomotives
}

class Locomotive {
  nameID
  owner
  type
  power
  acceleration
  topSpeed
  startYear
  fuelCost
  availabilityYear
  acquisitionPrice
  maintenancePrice
}

Player "1" -- "*" Scenario : plays >
Player "1" -- "*" Locomotive : buys >
Scenario "1" -- "*" Locomotive : configures >




@enduml