@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam class {
  BackgroundColor LightBlue
  BorderColor Blue
}
skinparam enum {
  BackgroundColor LightBlue
  BorderColor Blue
}
hide circle
hide methods

class Player {
  username
  password
  budget
}

class Scenario {
  nameID
  timeRestrictions
  technologicalRestrictions
  historicalRestrictions
}

class Locomotive {
  nameID
  type
  power
  acceleration
  topSpeed
  startYear
  fuelCost
  availabilityYear
  acquisitionPrice
  maintenancePrice
}

Player "1" -- "*" Scenario : plays >
Player "1" -- "*" Locomotive : buys >
Scenario "1" -- "*" Locomotive : configures >




@enduml