@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam class {
  BackgroundColor LightBlue
  BorderColor Blue
}


skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model: US03 - Add a city

class Editor {
   username
   password
   createdMaps
   createdScenarios
}

class Map {
  nameID
  cityList
  industryList
}

class Size {
  width
  height
}

class City {
  nameID
  trafficRate
  suppliedCargo
  demandedCargo
}

class HouseBlock {
  automaticPlacement
}

class Position {
  x
  y
  occupied
}

note left of City::houseBlocks
  houseBlocks have
  x and y coordinates
end note


Map "1" -- "*" City: contains

Editor "1" -- "*" City: adds
Editor "1" - "*" Map: creates

Map "1" -- "1" Size: has

Map "1" -- "*" Position : tracks >
HouseBlock "1" -- "1" Position : has >
City "1" -- "1" Position : located at >
@enduml
