@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

title Sequence Diagram: US10 - Assign a train to a route

actor "Player" as player
participant ":AssignTrainUI" as UI
participant ":AssignTrainController" as CTRL
participant ":RouteDTO" as ROUTE_DTO
participant ":PointOfRouteDTO" as POINT_DTO
participant ":TrainDTO" as TRAIN_DTO

activate player

note left of UI
    Retrieves available maps and scenarios and loads them
end note
    player -> UI : asks to assign a train
        activate UI
            UI -> CTRL**: create()
            UI -> CTRL: getAvailableRoutes()
            activate CTRL

            ref over CTRL
                Get RouteDTO List
            end

            CTRL --> UI: listRouteDTO
            deactivate CTRL
            UI --> player: displays list of available routes with valid stations
        deactivate UI

    player -> UI : selects a route
        activate UI
            UI -> ROUTE_DTO** : createRouteDTO(selectedRoute)
            UI -> CTRL: getRouteDetails(routeDTO)
            activate CTRL

            ref over CTRL
                Get Route Details DTO
            end

            CTRL --> UI: routeDetails
            deactivate CTRL
            UI --> player: displays route details (name, route points)
            UI --> player: asks for confirmation
        deactivate UI

    player -> UI : confirms route selection
        activate UI
            UI -> CTRL: getRoutePoints(routeDTO)
            activate CTRL

            ref over CTRL
                Get PointOfRouteDTO List
            end

            CTRL --> UI: listPointOfRouteDTO
            deactivate CTRL
            UI --> player: displays list of Points-of-Route
        deactivate UI

    loop for each Point-of-Route
        player -> UI : selects cargo mode (FULL/HALF/AVAILABLE)
            activate UI
            UI -> POINT_DTO** : createPointOfRouteDTO(pointOfRoute, cargoMode)
            UI -> CTRL: setCargoMode(pointOfRouteDTO)
            activate CTRL

            ref over CTRL
                Update PointOfRouteDTO
            end

            CTRL --> UI: success
            deactivate CTRL
    end

    UI -> CTRL: getAvailableTrains()
    activate CTRL

    ref over CTRL
        Get TrainDTO List
    end

    CTRL --> UI: listTrainDTO
    deactivate CTRL
    UI --> player: displays list of available trains
deactivate UI
    player -> UI : selects a train
        activate UI
            UI -> TRAIN_DTO** : createTrainDTO(selectedTrain)
            UI -> CTRL: getTrainDetails(trainDTO)
            activate CTRL

            ref over CTRL
                Get Train Details DTO
            end

            CTRL --> UI: trainDetails
            deactivate CTRL
            UI --> player: displays train details
            UI --> player: asks for confirmation
        deactivate UI

    player -> UI : confirms assignment
        activate UI
            UI -> CTRL: assignTrainToRoute(routeDTO, trainDTO)
            activate CTRL

            ref over CTRL
                Create Train-Route Assignment DTO
            end

            CTRL --> UI: assignmentDetails
            deactivate CTRL
            UI --> player: displays operation success
            UI --> player: displays train, route and station details (including list of cargoes to be picked up and cargo modes)
        deactivate UI

deactivate player

@enduml 