@startuml
skinparam packageStyle rectangle
skinparam shadowing false

participant ":StationBuildingController" as CTRL
participant "appSession\n:ApplicationSession" as APP_SESSION
participant "map\n:Map" as MAP

autonumber 21
-> CTRL : getClosestCity(position)

autonumber 21.1
activate CTRL
    group Get Closest City
        CTRL -> APP_SESSION: getInstance()
        activate APP_SESSION
            APP_SESSION --> CTRL: sessionInstance
        deactivate APP_SESSION

        CTRL -> APP_SESSION: getCurrentMap()
        activate APP_SESSION
            APP_SESSION --> CTRL: currentMap
        deactivate APP_SESSION

        CTRL -> MAP: getClosestCity(position)
        activate MAP
            MAP --> CTRL: closestCity
        deactivate MAP
    end

    autonumber 22
    <-- CTRL : closestCity
deactivate CTRL

@enduml 