@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":StationBuildingController" as CTRL
participant "mapRepository\n:MapRepository" as MAP_REPO
participant "maps\n:Maps" as MAPS
participant "map\n:Map" as MAP
participant "scenarios:Scenarios" as SCNS
participant "scenario:Scenario" as SCN
participant "stations\n:Stations" as STATIONS
participant ":StationMapper" as STATION_MAPPER
participant "stationDTO\n:StationDTO" as STATION_DTO
participant "station\n:Station" as STATION

autonumber 22
-> CTRL: buildStation(stationDTO)

autonumber 22.1
activate CTRL
    group Create Station Object


        CTRL -> MAP_REPO: createStation(stationDTO)
        activate MAP_REPO
            MAP_REPO -> MAPS: createStation(stationDTO)
            activate MAPS
            MAPS -> MAP: createStation(stationDTO)
            activate MAP
            MAP -> SCNS: createStation(stationDTO)
            activate SCNS
            SCNS -> SCN: createStation(stationDTO)
            activate SCN
            SCN -> STATIONS: createStation(stationDTO)
            activate STATIONS
                STATIONS -> STATION_MAPPER: station = toModel(stationDTO)
                activate STATION_MAPPER
                    STATION_MAPPER -> STATION_DTO: stationType = getStationType()
                    activate STATION_DTO
                    deactivate STATION_DTO

                    STATION_MAPPER -> STATION_DTO: position = getPosition()
                    activate STATION_DTO
                        STATION_DTO --> STATION_MAPPER: position
                    deactivate STATION_DTO

                    STATION_MAPPER -> STATION_DTO: defaultBuilding = getDefaultBuilding()
                    activate STATION_DTO
                    deactivate STATION_DTO

                    STATION_MAPPER -> STATION_DTO: proposedName = getProposedName()
                    activate STATION_DTO
                    deactivate STATION_DTO

                    STATION_MAPPER -> STATION**: create(stationType, position, defaultBuilding, proposedName)
                deactivate STATION_MAPPER

                STATIONS -> STATIONS: addStation(station)
                activate STATIONS
                    STATIONS -> STATIONS: validateStation(station)
                    activate STATIONS
                        STATIONS --> STATIONS: true
                        deactivate STATIONS
                    STATIONS --> STATIONS: true
                    deactivate STATIONS

                    STATIONS -> STATION: occupyPosition()
                    activate STATION
                        STATION -> STATION: position.setOccupied(true)
                        STATION --> STATIONS: success
                    deactivate STATION

                    STATIONS --> SCN: success
                    deactivate STATIONS
                    SCN --> SCNS: success
                    deactivate SCN
                    SCNS --> MAP: success
                    deactivate SCNS
                    MAP --> MAPS: success
                    deactivate MAP
                    MAPS --> MAP_REPO: success
                    deactivate MAPS
            MAP_REPO --> CTRL: success
        deactivate MAP_REPO

    end

    autonumber 23
    <-- CTRL : success
deactivate CTRL

@enduml 