@startuml
skinparam packageStyle rectangle
skinparam shadowing false

participant ":StationBuildingController" as CTRL
participant "appSession\n:ApplicationSession" as APP_SESSION
participant "map\n:Map" as MAP
participant "player\n:Player" as PLAYER
participant "stationType\n:StationType" as TYPE
participant "closestCity\n:City" as CITY
participant "station\n:Station" as STATION

autonumber 35
-> CTRL : buildStation(stationType, position, centerPoint)

autonumber 35.1
activate CTRL
    group Build Station
        CTRL -> APP_SESSION: getInstance()
        activate APP_SESSION
            APP_SESSION --> CTRL: sessionInstance
        deactivate APP_SESSION

        CTRL -> APP_SESSION: getCurrentMap()
        activate APP_SESSION
            APP_SESSION --> CTRL: currentMap
        deactivate APP_SESSION
        
        CTRL -> APP_SESSION: getCurrentSession()
        activate APP_SESSION
            APP_SESSION --> CTRL: player
        deactivate APP_SESSION
        
        CTRL -> MAP: getClosestCity(position)
        activate MAP
            MAP --> CTRL: closestCity
        deactivate MAP
        
        CTRL -> CITY: getNameID()
        activate CITY
            CITY --> CTRL: cityName
        deactivate CITY
        
        CTRL -> TYPE: getCost()
        activate TYPE
            TYPE --> CTRL: cost
        deactivate TYPE
        
        CTRL -> PLAYER: deductFromBudget(cost)
        activate PLAYER
            PLAYER --> CTRL: success
        deactivate PLAYER
        
        CTRL -> STATION**: new Station(cityName + stationType.name, position, stationType)
        
        CTRL -> MAP: addStation(station)
        activate MAP
            MAP --> CTRL: success
        deactivate MAP
    end

    autonumber 36
    <-- CTRL : success
deactivate CTRL

@enduml 