@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":StationBuildingController" as CTRL

participant "mapRepository\n:MapRepository" as MAP_REPO
participant "maps\n:Maps" as MAPS
participant "map\n:Map" as MAP
participant "cities\n:Cities" as CITIES
participant ":List<City>" as CITY_LIST
participant ":City" as CITY

autonumber 3
-> CTRL: getClosestCity(position)

autonumber 3.1
activate CTRL
    group Get Closest City

        CTRL -> MAP_REPO: getListOfCities()
        activate MAP_REPO
            MAP_REPO -> MAPS: getListOfCities()
            activate MAPS
            MAPS -> MAP: getListOfCities()
            activate MAP
            MAP  -> CITIES: getListOfCities()
            activate CITIES
                CITIES --> CITY_LIST**: create()

                loop for each known City
                    CITIES -> CITY_LIST: city = get(i)
                    activate CITY_LIST
                        deactivate CITY_LIST

                    CITIES -> CITY_LIST: add(city)
                    activate CITY_LIST
                        deactivate CITY_LIST
                end

                CITIES --> MAP: cityList
            deactivate CITIES
            MAP --> MAPS: cityList
            deactivate MAP
            MAPS --> MAP_REPO: cityList
        deactivate MAPS

            MAP_REPO --> CTRL: cityList
        deactivate MAP_REPO

        loop for each city in cityList
            CTRL -> CITY: getPosition()
            activate CITY
                CITY --> CTRL: cityPosition
            deactivate CITY

            CTRL -> CTRL: calculateDistance(position, cityPosition)
            activate CTRL
                CTRL --> CTRL: distance
            deactivate CTRL

            CTRL -> CTRL: updateClosestCity(city, distance)
            activate CTRL
                deactivate CTRL
        end

        CTRL -> CTRL: getClosestCityName()
        activate CTRL
            CTRL --> CTRL: cityName
        deactivate CTRL

    end

    autonumber 4
    <-- CTRL : cityName
deactivate CTRL

@enduml
