@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

title Sequence Diagram: US01 - Create a Map

actor "Editor" as editor
participant ":CreateMapUI" as UI
participant ":CreateMapController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "mapRepository\n:MapRepository" as REPOS_MAP
participant "ApplicationSession" as APP_SESSION
participant "appSession\n:ApplicationSession" as APP_SESSION_SINGLETON
participant "editor\n:Editor" as EDITOR
participant "Map" as MAP
participant "Size" as SIZE

activate editor

    editor -> UI : asks to create a new map
        activate UI
            UI -> CTRL**: create()
            UI --> editor: requests map data (name, width, height)
        deactivate UI

    editor -> UI: inputs requested data
        activate UI
            UI -> CTRL: validateMapData(nameID, width, height)
            activate CTRL
                ' Order changed to validate name first, since it's input first
                CTRL -> MAP: validateMapName(nameID)
                activate MAP
                    MAP --> CTRL: valid
                deactivate MAP
                
                CTRL -> SIZE: validateSize(width, height)
                activate SIZE
                    SIZE --> CTRL: valid
                deactivate SIZE
                
                CTRL --> UI: valid
            deactivate CTRL
            UI --> editor: shows map data and requests confirmation
        deactivate UI

    editor -> UI: confirms data
        activate UI
            UI -> CTRL: createMap(nameID, width, height)
            activate CTRL
                CTRL -> APP_SESSION: getInstance()
                activate APP_SESSION
                    APP_SESSION --> CTRL: appSession
                deactivate APP_SESSION
                
                CTRL -> APP_SESSION_SINGLETON: getCurrentSession()
                activate APP_SESSION_SINGLETON
                    APP_SESSION_SINGLETON --> CTRL: editor
                deactivate APP_SESSION_SINGLETON
                
                ' Create a Size instance
                CTRL -> SIZE**: createSize(width, height)


                CTRL -> EDITOR: createMap(nameID, size)
                activate EDITOR
                    EDITOR -> MAP**: createMap(nameID, size)

                    EDITOR -> EDITOR: addMap(map)
                    EDITOR --> CTRL: map
                deactivate EDITOR
                
                CTRL -> REPOS: getInstance()
                activate REPOS
                    REPOS --> CTRL: repositories
                deactivate REPOS
                
                CTRL -> REPOS_SINGLETON: getMapRepository()
                activate REPOS_SINGLETON
                    REPOS_SINGLETON --> CTRL: mapRepository
                deactivate REPOS_SINGLETON
                
                CTRL -> REPOS_MAP: save(map)
                activate REPOS_MAP
                    REPOS_MAP --> CTRL: success
                deactivate REPOS_MAP
                
                CTRL --> UI: success + mapDetails
            deactivate CTRL
            
            UI --> editor: displays operation success
            UI --> editor: displays map details
        deactivate UI

deactivate editor

@enduml
