@startuml
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

actor Editor
participant ":CreateMapUI" as UI
participant ":CreateMapController" as CTRL
participant "Repositories" as REPOS
participant "mapRepository\n:MapRepository" as MAP_REPO
participant "ApplicationSession" as APP_SESSION
participant "currentSession\n:UserSession" as USER_SESSION
participant "editor\n:Editor" as EDITOR
participant "map\n:Map" as MAP
participant "size\n:Size" as SIZE

Editor -> UI : confirms creation
activate UI
    UI -> CTRL : createNewMap(name, width, height)
    activate CTRL
        CTRL -> APP_SESSION : getInstance()
        activate APP_SESSION
            APP_SESSION --> CTRL : appSession
        deactivate APP_SESSION

        CTRL -> USER_SESSION : getCurrentEditor()
        activate USER_SESSION
            USER_SESSION --> CTRL : editor
        deactivate USER_SESSION

        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL : repositories
        deactivate REPOS

        CTRL -> MAP_REPO : saveMap(map)
        activate MAP_REPO
            MAP_REPO --> CTRL : saveResult
        deactivate MAP_REPO

        CTRL -> EDITOR : createMap(name, width, height)
        activate EDITOR
            EDITOR -> MAP : create(name, width, height)
            activate MAP
                MAP -> SIZE : create(width, height)
                activate SIZE
                    SIZE --> MAP : size
                deactivate SIZE
                MAP --> EDITOR : newMap
            deactivate MAP
            EDITOR --> CTRL : newMap
        deactivate EDITOR

        CTRL --> UI : creationResult
    deactivate CTRL
    UI --> Editor : displays operation success
deactivate UI
@enduml