@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model US03

class Player {
    username
    password
    budget
  }

class Station {
    name
    xAxis
    yAxis
    type: StationType
    radius
    cost
  }

class Cargo {
   amount
   lifespan
  }

class Building {
    name
    upgradeLevel
    availableYear
    cost
    effect
  }

  class StationBuildingSlot {
    category: BuildingCategory
    upgradeDate
  }

Player "1" -- "1" Station : selects >
Station "1" -- "*" Cargo : stores >
Station "1" -- "1..*" StationBuildingSlot : has >
StationBuildingSlot "1" -- "0..1" Building : contains >

@enduml