@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":CreateScenarioController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "industryRepository\n:IndustryRepository" as INDUSTRY_REPO

autonumber 7
-> CTRL : getAvailableIndustries(startDate, endDate)
autonumber 7.1
activate CTRL
    group Get Available Industries
        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL: repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON : getIndustryRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL: industryRepository
        deactivate REPOS_SINGLETON

        CTRL -> INDUSTRY_REPO : getAvailableIndustries(startDate, endDate)
        activate INDUSTRY_REPO
            INDUSTRY_REPO --> CTRL : availableIndustriesList
        deactivate INDUSTRY_REPO
    end

    autonumber 8
    <-- CTRL : availableIndustriesList
deactivate CTRL

@enduml 