@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateScenarioController" as CTRL
participant "editorRepository\n:EditorRepository" as EDITOR_REPO

autonumber 37
-> CTRL : addScenarioToEditor(editor, scenario)

autonumber 37.1
activate CTRL
    group Add Scenario to Editor
        CTRL -> EDITOR_REPO : addScenarioToEditor(editor, scenario)
        activate EDITOR_REPO
            EDITOR_REPO --> CTRL : true
        deactivate EDITOR_REPO
    end

    autonumber 38
    <-- CTRL : true
deactivate CTRL

@enduml 