@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Editor" as Editor
participant ":System" as System

activate Editor

Editor -> System : "Request to add a new city"
activate System
System -> Editor : "Request for each map he wants to add the city to"
deactivate System
Editor -> System : "Selects the map he wants to add a new city to"
activate System
System -> Editor : "Request for the city name"
deactivate System
Editor -> System : "Enters the name of the city"
activate System
System -> System : "Check if there isn’t special digits or characters in the name"
System -> Editor : "Request the coordinates of the city"
deactivate System
Editor -> System : "Enters the coordinates of the city"
activate System
System -> System : "Validate the coordinates of the city"
System -> Editor : "Request the number of house blocks"
deactivate System
Editor -> System : "Enters the number of house blocks"
activate System
System -> System : "Check if the number of house blocks is a positive number"
System -> Editor : "Ask if the editor wants to assign the blocks manually or automatically"
deactivate System
Editor -> System : "Selects yes or no"
activate System

group if [while answer is yes]
    System --> Editor : "Requests house blocks position"
    deactivate System

    Editor -> System : "Selects blocks position"
    activate System
    System -> System : "Check if the position is valid"
    System -> Editor : "Asks if the editor wants to assign the next block manually"

    deactivate System
    Editor -> System : "Selects yes or no"
else if [answer is no]
System --> Editor : assigns house blocks automatically

end if
System -> Editor : "City added successfully"
System -> Editor : "List the cities in the map"
System -> Editor : "List the Details of the city that was added (name, position, number of house blocks, map)"

deactivate System
deactivate Editor
@enduml
