@startuml
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

title System Sequence Diagram: US04 - Create a Scenario

actor "Editor" as Editor
participant ":System" as System

activate Editor

    Editor -> System : asks to create a scenario
    activate System

        System --> Editor : shows map list and asks to select one
    deactivate System

    Editor -> System : selects a map
    activate System

        System --> Editor : requests data (name, start date, end date)
    deactivate System

    Editor -> System : types requested data
    activate System

        System --> Editor : shows a list of locomotive types\nand asks to select the available ones
    deactivate System

    Editor -> System : selects available locomotive types
    activate System

        System --> Editor : shows list of industries\nand requests data (available industries, \n ports behavior, generation factors)
    deactivate System

    Editor -> System : types requested data
    activate System

        System --> Editor : show all data and requests confirmation
    deactivate System

        Editor -> System : confirms data
    activate System

        System --> Editor : displays operation success
    deactivate System

@enduml