@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

title "System Sequence Diagram - US10 : Assign a train to a route"

actor "Player" as Player
participant ":System" as System

activate Player



    Player -> System : asks to assign a train
        activate System
            System --> Player : displays list of available routes with valid stations
        deactivate System

    Player -> System : selects a route
        activate System
            System --> Player : displays route details (name, station stops)
            System --> Player : asks for confirmation
        deactivate System

    Player -> System : confirms assignment
        activate System
            System --> Player : displays operation success
            System --> Player : displays train, route and station details (including  list of cargoes to be picked up)
        deactivate System



@enduml