@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Editor" as EDITOR
participant ":AddIndustryUI" as UI
participant ":AddIndustryController" as CTRL
participant "industryDTO\n:IndustryDTO" as DTO_IND

activate EDITOR

    EDITOR -> UI : asks to add an industry
    activate UI
        UI --> CTRL** : create()
        UI -> CTRL : getListOfMaps()

        ref over CTRL
            Get MapDTO List
        end ref

        activate CTRL
            CTRL --> UI : listMapDTO
        deactivate CTRL

        UI --> EDITOR : shows a list of available maps
    deactivate UI

    EDITOR -> UI : selects a map
    activate UI
        UI -> CTRL : loadMap(mapDTO)

        ref over CTRL
            Load Selected Map
        end ref

        activate CTRL
            CTRL --> UI : mapLayout
        deactivate CTRL

        UI --> EDITOR : displays the selected map
    deactivate UI

    EDITOR -> UI : confirms the selected map
    activate UI
        UI -> CTRL : getListOfIndustrySectors()

        ref over CTRL
            Get IndustrySectorDTO List
        end ref

        activate CTRL
            CTRL --> UI : listIndustrySectorDTO
        deactivate CTRL

        UI --> EDITOR : shows a list of industry sectors
    deactivate UI

    EDITOR -> UI : selects an industry sector
    activate UI
        UI --> EDITOR : asks for industry data(nameID, X and Y coordinates, availabilityYear, suppliedCargo, demandedCargo)
    deactivate UI

    EDITOR -> UI : provides industry data(nameID, X and Y coordinates, availabilityYear, suppliedCargo, demandedCargo)
    activate UI
        UI -> CTRL : addIndustry(nameID, X and Y coordinates, sector, availabilityYear, suppliedCargo, demandedCargo)

        activate CTRL
            CTRL -> DTO_IND** : create(nameID, X, Y, sector, availabilityYear, suppliedCargo, demandedCargo)

            CTRL --> UI : industryDTO
        deactivate CTRL

        UI --> EDITOR : shows industry data and asks for confirmation
    deactivate UI

    EDITOR -> UI : confirms the data
    activate UI
        UI -> CTRL : createAndAddIndustry(currentMap, industryDTO)

        ref over CTRL
            Create and Add Industry
        end ref

        activate CTRL
            CTRL --> UI : success
        deactivate CTRL

        UI --> EDITOR : displays success message
    deactivate UI

deactivate EDITOR
@enduml
