@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam sequenceMessageAlign center

title Sequence Diagram: US02 - Add Industry

autonumber

actor "Editor" as editor
participant ":AddIndustryUI" as UI
participant ":AddIndustryController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant ":ApplicationSession" as APP_SESSION

participant "mapRepository\n:MapRepository" as REPOS_MAP
participant "mapMapper\n:MapMapper" as MAPPER_MAP
participant "listMap : List<Map>" as LIST_MAP
participant "maps\n:Maps" as MAPS
participant "listMapDTO\n:List<MapDTO>" as LIST_MAP_DTO
participant "mapDTO\n:MapDTO" as DTO_MAP
participant "currentMap\n:Map" as MAP


participant "industrySectorRepository\n:IndustrySectorRepository" as IND_SECTOR_REPO
participant "industrySectors:IndustrySectors" as IND_SECTORS
participant ":List<IndustrySector>" as LIST
participant ":IndustrySectorMapper" as IND_SECTOR_MAPPER
participant "listIndustrySector\n:List<IndustrySector>" as IND_SECTOR_LIST
participant "listIndustrySectorDTO\n:List<IndustrySectorDTO>" as IND_SECTOR_LIST_DTO
participant "industrySectorDTO\n:IndustrySectorDTO" as IND_SECTOR_DTO

participant "industries\n:Industries" as INDS
participant ":List<Industry>" as LIST
participant ":IndustryMapper" as IND_MAPPER
participant "industryDTO\n:IndustryDTO" as DTO_IND
participant "Industry\n:Industry" as IND
participant "listIndustry\n:List<Industry>" as IND_LIST
participant "listIndustryDTO\n:List<IndustryDTO>" as IND_LIST_DTO
participant "industryRepository\n:IndustryRepository" as REPOS_IND

participant "positions\n:Positions" as POSITIONS
participant "position\n:Position" as POS

activate editor

editor -> UI : Asks to add an industry
activate UI

    UI -> CTRL**: create()

    UI -> CTRL: getListOfMaps()
    activate CTRL
        group Get Available Maps
        autonumber 3.1
            CTRL -> REPOS: getInstance()
            activate REPOS
                REPOS --> CTRL : repositories
            deactivate REPOS

            CTRL -> REPOS_SINGLETON : getMapRepository()
            activate REPOS_SINGLETON
                REPOS_SINGLETON --> CTRL : mapRepository
            deactivate REPOS_SINGLETON

            CTRL -> REPOS_MAP : getListOfMaps()
            activate REPOS_MAP
                REPOS_MAP -> LIST_MAP**: create()
                REPOS_MAP --> CTRL : List<Map>
            deactivate REPOS_MAP

            CTRL -> MAPPER_MAP : toMapDTOs(List<Map>)
            activate MAPPER_MAP
                loop for each map in List<Map>
                MAPPER_MAP -> LIST_MAP: obj = get(i)
                activate LIST_MAP
                deactivate LIST_MAP

                MAPPER_MAP -> MAPPER_MAP : objDTO = toDTO(obj)
                activate MAPPER_MAP
                deactivate MAPPER_MAP

                MAPPER_MAP -> DTO_MAP**: create(...)
                MAPPER_MAP --> LIST_MAP_DTO : add(mapDTO)
                activate LIST_MAP_DTO
                deactivate LIST_MAP_DTO

                end
                MAPPER_MAP --> CTRL : listMapDTO
            deactivate MAPPER_MAP
        end
        autonumber 4
        CTRL --> UI: listMapDTO
    deactivate CTRL

    UI --> editor: Shows the list of available maps
deactivate UI

editor -> UI: Selects a map
activate UI
    UI -> CTRL: loadMap(mapDTO)
    activate CTRL
        group Load Selected Map
        autonumber 7.1

            CTRL -> DTO_MAP: getNameID()
            activate DTO_MAP
                DTO_MAP --> CTRL : nameID
            deactivate DTO_MAP

            CTRL -> REPOS_MAP : getMapById(mapId)
            activate REPOS_MAP
            REPOS_MAP -> MAPS: getMapById(mapId)
                activate MAPS
                    MAPS --> REPOS_MAP: currentMap
                deactivate MAPS
                REPOS_MAP --> CTRL : currentMap
            deactivate REPOS_MAP

            CTRL -> MAP: getMapLayout()
            activate MAP
            MAP --> CTRL: mapLayout
            deactivate MAP
            autonumber 8
        end
        CTRL --> UI: mapLayout
    deactivate CTRL
    UI --> editor: Loads and displays the selected map
deactivate UI

editor -> UI: Confirms the selected map
activate UI

    UI -> CTRL: getListOfIndustrySectors()
    autoNumber 11.1
    activate CTRL
        group Get IndustrySectorDTO List

            CTRL -> REPOS_SINGLETON: getIndustrySectorRepository()
            activate REPOS_SINGLETON
                REPOS_SINGLETON --> CTRL: industrySectorRepository
            deactivate REPOS_SINGLETON

            CTRL -> IND_SECTOR_REPO: getListOfIndustrySectors()
            activate IND_SECTOR_REPO

            IND_SECTOR_REPO -> IND_SECTORS: getListOfIndustrySectors()
            activate IND_SECTORS

                IND_SECTORS --> IND_SECTOR_LIST**: create()

                loop for each known IndustrySector
                    IND_SECTORS -> LIST: industrySector = get(i)
                    activate LIST
                        deactivate LIST

                    IND_SECTORS -> IND_SECTOR_LIST: add(industrySector)
                    activate IND_SECTOR_LIST
                        deactivate IND_SECTOR_LIST
                end

                IND_SECTORS --> IND_SECTOR_REPO: listIndustrySector
                deactivate IND_SECTORS

                IND_SECTOR_REPO --> CTRL: listIndustrySector
                deactivate IND_SECTOR_REPO

            CTRL -> IND_SECTOR_MAPPER: toDTO(listIndustrySector)
            activate IND_SECTOR_MAPPER

                IND_SECTOR_MAPPER --> IND_SECTOR_LIST_DTO**: create()

                loop for each object in listIndustrySector
                    IND_SECTOR_MAPPER -> IND_SECTOR_LIST: industrySector = get(i)
                    activate IND_SECTOR_LIST
                        deactivate IND_SECTOR_LIST

                    IND_SECTOR_MAPPER -> IND_SECTOR_MAPPER: industrySectorDTO = toDTO(industrySector)
                    activate IND_SECTOR_MAPPER
                        IND_SECTOR_MAPPER --> IND_SECTOR_DTO**: create()
                        deactivate IND_SECTOR_MAPPER

                    IND_SECTOR_MAPPER -> IND_SECTOR_LIST_DTO: add(industrySectorDTO)
                    activate IND_SECTOR_LIST_DTO
                        deactivate IND_SECTOR_LIST_DTO
                end

            IND_SECTOR_MAPPER --> CTRL: listIndustrySectorDTO
            deactivate IND_SECTOR_MAPPER

        end

        autonumber 12
        CTRL --> UI : listIndustrySectorDTO
    deactivate CTRL
    UI --> editor : Shows the list of industry sectors
deactivate UI

editor -> UI : Selects an industry sector
activate UI
UI --> editor : Asks for industry data(nameID, X and Y coordinates, availabilityYear, suppliedCargo, demandedCargo)
deactivate UI

editor -> UI : Provides industry data (nameID, X and Y coordinates, availabilityYear, suppliedCargo, demandedCargo)
activate UI

    UI -> CTRL : addIndustry(nameID, X and Y coordinates, sector, availabilityYear, suppliedCargo, demandedCargo)
    activate CTRL
        ' The Controller creates the DTO for validation and confirmation.
        CTRL -> DTO_IND**: create(nameID, X and Y coordinates, sector, availabilityYear, suppliedCargo, demandedCargo)
        CTRL --> UI : industryDTO
    deactivate CTRL

    UI --> editor : Shows industry data and asks for confirmation
deactivate UI

editor -> UI : Confirms the data
activate UI
    UI -> CTRL : createAndAddIndustry(mapDTO, industryDTO)
        activate CTRL
        autonumber 22.1
            group Create and Add Industry

            CTRL ->  MAPS :createAndAddIndustry(currentMap, industryDTO)
                activate MAPS
                MAPS -> MAP: createAndAddIndustry(industryDTO)
                activate MAP
                    MAP -> POSITIONS : isPositionAvailable(industryDTO.getX(), industryDTO.getY())
                    activate POSITIONS
                        POSITIONS -> POS : isAvailable()
                        activate POS
                            POS --> POSITIONS : true
                        deactivate POS
                        POSITIONS --> MAP : success
                    deactivate POSITIONS


                    MAP -> INDS: AddIndustry(industryDTO)
                    activate INDS
                        INDS -> IND_MAPPER : industry = toDomain(industryDTO)
                        activate IND_MAPPER
                            IND_MAPPER -> DTO_IND : nameID = getNameID()
                            activate DTO_IND
                            deactivate DTO_IND
                            IND_MAPPER -> DTO_IND : type = getType()
                            activate DTO_IND
                            deactivate DTO_IND
                            IND_MAPPER -> DTO_IND : position = getPosition()
                            activate DTO_IND
                            deactivate DTO_IND
                            IND_MAPPER -> DTO_IND : availabilityYear = getAvailabilityYear()
                            activate DTO_IND
                            deactivate DTO_IND
                            IND_MAPPER -> DTO_IND : demandedCargo = getDemandedCargo()
                            activate DTO_IND
                            deactivate DTO_IND
                            IND_MAPPER -> DTO_IND : suppliedCargo = getSuppliedCargo()
                            activate DTO_IND
                            deactivate DTO_IND
                            IND_MAPPER -> IND** : create(nameID, type, position, availabilityYear, demandedCargo, suppliedCargo)
                        deactivate IND_MAPPER

                        INDS -> INDS : add(industry)
                        activate INDS
                        INDS --> INDS : true
                        deactivate INDS


                        INDS --> MAP : success

                    deactivate INDS
                    MAP -> POSITIONS : setOcuppied(industryDTO.getX(), industryDTO.getY())
                    activate POSITIONS
                        POSITIONS -> POS : setOcuppied()
                        activate POS
                            POS --> POSITIONS : success
                        deactivate POS
                        POSITIONS --> MAP : success
                    deactivate POSITIONS
                    MAP --> MAPS : success
                deactivate MAP
                MAPS --> CTRL : success
            deactivate MAPS


            ' Success response
            end
            autonumber 23
            CTRL --> UI : success
        deactivate CTRL
    UI --> editor : displays success message
    deactivate UI

deactivate editor
@enduml