@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

title System Sequence Diagram : US03 - Add a city

actor "Editor" as Editor
participant ":System" as AddCityUI

activate Editor
Editor -> AddCityUI : asks to add city
        activate AddCityUI


        AddCityUI --> Editor: shows a list of Maps
        deactivate AddCityUI
        Editor -> AddCityUI: selects a map
        activate AddCityUI
        AddCityUI --> Editor : asks for city name
        deactivate AddCityUI


    Editor -> AddCityUI: inputs name

        activate AddCityUI
        AddCityUI --> Editor: asks for coordinates
        deactivate AddCityUI
    Editor -> AddCityUI: inputs coordinates
        activate AddCityUI

        AddCityUI --> Editor: asks number of house blocks
        deactivate AddCityUI
    Editor -> AddCityUI: inputs number
        activate AddCityUI

        AddCityUI --> Editor: asks if the editor wants to assign the blocks manually or automatically
        deactivate AddCityUI
    Editor -> AddCityUI: selects yes/no
        activate AddCityUI
        AddCityUI --> AddCityUI: assign blocks
        AddCityUI --> Editor: asks for confirmation
        deactivate AddCityUI
        Editor -> AddCityUI: confirms

        activate AddCityUI
        AddCityUI --> Editor: display city details + success

        deactivate AddCityUI


@enduml