@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":UpgradeStationController" as CTRL
participant "stations\n:Stations" as STATIONS
participant "currentStation\n:Station" as STATION
participant "buildings\n:Buildings" as BUILDINGS
participant "buildingMapper\n:BuildingMapper" as MAPPER_BUILDING
participant "buildingDTO\n:BuildingDTO" as DTO_BUILDING
participant "Building\n:Building" as BUILDING
participant "applicationSession\n:ApplicationSession" as APP_SESSION_SINGLETON

autonumber 19

 -> CTRL : upgradeStation(currentStation, buildingDTO)
        activate CTRL
        autonumber 19.1
            group Upgrade Station

            ' Go through Scenario to manage the upgrade (Scenario configures stations)
            CTRL -> STATIONS: upgradeStation(currentStation, buildingDTO)
                activate STATIONS
                STATIONS -> STATION: upgradeStation(buildingDTO)
                activate STATION
                STATION -> BUILDINGS: upgradeStation(buildingDTO)
                activate BUILDINGS
                BUILDINGS -> MAPPER_BUILDING: building = toDomain(buildingDTO)
                activate MAPPER_BUILDING
                    MAPPER_BUILDING -> DTO_BUILDING: nameID = getNameID()
                    activate DTO_BUILDING
                    deactivate DTO_BUILDING
                    MAPPER_BUILDING -> DTO_BUILDING: type = getType()
                    activate DTO_BUILDING
                    deactivate DTO_BUILDING
                    MAPPER_BUILDING -> DTO_BUILDING: availabilityYear = getAvailabilityYear()
                    activate DTO_BUILDING
                    deactivate DTO_BUILDING
                    MAPPER_BUILDING -> DTO_BUILDING: evolutionCost = getEvolutionCost()
                    activate DTO_BUILDING
                    deactivate DTO_BUILDING
                    MAPPER_BUILDING -> DTO_BUILDING: evolutionStagesLeft = getEvolutionStagesLeft()
                    activate DTO_BUILDING
                    deactivate DTO_BUILDING
                    MAPPER_BUILDING -> DTO_BUILDING: effect = getEffect()
                    activate DTO_BUILDING
                    deactivate DTO_BUILDING
                    MAPPER_BUILDING -> BUILDING** : create(nameID, type, availabilityYear, evolutionCost, evolutionStagesLeft, effect)
                    deactivate MAPPER_BUILDING

                    BUILDINGS -> BUILDINGS : addBuilding(building)
                    activate BUILDINGS
                        BUILDINGS --> BUILDINGS : success
                    deactivate BUILDINGS

                    BUILDINGS --> STATION : success
                deactivate BUILDINGS
                STATION --> STATIONS : success
                deactivate STATION
                STATIONS --> CTRL : success
                deactivate STATIONS
                CTRL -> APP_SESSION_SINGLETON: upgradePlayerBudget(evolutionCost)
                activate APP_SESSION_SINGLETON
                    APP_SESSION_SINGLETON -> APP_SESSION_SINGLETON: getCurrentPlayer()
                    activate APP_SESSION_SINGLETON
                        APP_SESSION_SINGLETON --> APP_SESSION_SINGLETON : currentPlayer
                    deactivate APP_SESSION_SINGLETON

                    ' Update player's budget based on upgrade cost
                    APP_SESSION_SINGLETON -> APP_SESSION_SINGLETON : updatePlayerBudget(currentPlayer, evolutionCost)
                    activate APP_SESSION_SINGLETON
                        APP_SESSION_SINGLETON --> APP_SESSION_SINGLETON : success
                    deactivate APP_SESSION_SINGLETON
                    APP_SESSION_SINGLETON --> CTRL : success
                deactivate APP_SESSION_SINGLETON
                end
                autonumber 20

                <-- CTRL : success
                deactivate CTRL

@enduml