@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber 3

participant ":UpgradeStationController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "ApplicationSession" as APP_SESSION
participant "stationRepository\n:StationRepository" as REPOS_STATION
participant ":station\nStation" as station

-> CTRL: getAvailableUpgrades()
activate CTRL
autonumber 3.1
group Get Available Upgrades
    CTRL -> REPOS: getInstance()
        activate REPOS
            REPOS --> CTRL: repositories
        deactivate REPOS

    CTRL -> REPOS_SINGLETON: getStationRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL: stationRepository
        deactivate REPOS_SINGLETON

    CTRL -> APP_SESSION: getInstance()
        activate APP_SESSION
            APP_SESSION --> CTRL: stationId = appSession
        deactivate APP_SESSION

    CTRL -> REPOS_STATION: getStation(stationId)
        activate REPOS_STATION
            REPOS_STATION --> CTRL: station
        deactivate REPOS_STATION

    CTRL -> station: getAvailableUpgrades(station)
        activate station
        station --> CTRL: availableUpgrades
        deactivate station
end
autonumber 4

<-- CTRL : availableUpgrades

deactivate CTRL

@enduml