@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

title System Sequence Diagram: US06 - Upgrade a selected station with a building

actor "Player" as PLAYER
participant ":UpgradeStationUI" as UI
participant ":UpgradeStationController" as CTRL

activate PLAYER

PLAYER -> UI : Asks to upgrade a station
activate UI

UI -> CTRL** : create()
UI -> CTRL : getListOfStationsDTO()
activate CTRL
ref over CTRL : Get StationsDTO List
CTRL --> UI : listStationDTO
deactivate CTRL

UI --> PLAYER : Shows the list of available stations
deactivate UI

PLAYER -> UI : Selects a station
activate UI
UI -> CTRL : loadStation(stationDTO)
activate CTRL
ref over CTRL : Load Selected Station
CTRL --> UI : stationDetails
deactivate CTRL
UI --> PLAYER : Loads and displays the selected station details
deactivate UI

PLAYER -> UI : Confirms the selected station
activate UI
UI -> CTRL : getListOfAvailableBuildings()
activate CTRL
ref over CTRL : Get Available Building DTOs
CTRL --> UI : listBuildingDTO
deactivate CTRL
UI --> PLAYER : Shows the list of available buildings for upgrade
deactivate UI

PLAYER -> UI : Selects a building
activate UI
UI -> CTRL : getBuildingInfo(buildingDTO)
activate CTRL
ref over CTRL : Get Building Info
CTRL --> UI : buildingDetails
deactivate CTRL
UI --> PLAYER : Shows building details and asks for confirmation
deactivate UI

PLAYER -> UI : Confirms the upgrade
activate UI
UI -> CTRL : upgradeStation(currentStation, buildingDTO)
activate CTRL
ref over CTRL : Upgrade Station
CTRL --> UI : success
deactivate CTRL
UI --> PLAYER : Displays success message
deactivate UI

deactivate PLAYER
@enduml
