@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

title System Sequence Diagram: US04 - Create a Scenario

actor "Editor" as Editor
participant ":System" as System

activate Editor

    Editor -> System : asks to create a scenario
    activate System

        System --> Editor : requests name and time restrictions (i.e. start and end date)
    deactivate System

    Editor -> System : types requested data
    activate System

        System --> Editor : requests the historical events
    deactivate System

    Editor -> System : types the historical events
    activate System

    loop while port exist (mixed industries)
            System --> Editor : shows a list of cargoes and asks to select the ones the port import
        deactivate System

        Editor -> System : selects the cargoes the port import
        activate System

            System --> Editor : shows a list of cargoes and asks to select the ones the port export
        deactivate System

            Editor -> System : selects the cargoes the port export
            activate System

            System --> Editor : shows a list of cargoes and asks to select the ones the port transform
        deactivate System

            Editor -> System : selects the cargoes the port transform
            activate System
    end

        System --> Editor : shows a list of industries and asks to select the ones available in the scenario
    deactivate System

    Editor -> System : selects the available industries in the scenario
    activate System

    loop while generating industry exist
            System --> Editor : requests the industry generating frequency factor
        deactivate System

        Editor -> System : types the generating industry factor
        activate System
    end

            System --> Editor : shows a list of locomotive types and asks to select the available ones
        deactivate System

        Editor -> System : selects the available locomotive types
        activate System

        System --> Editor : shows all data and requests confirmation
    deactivate System

    Editor -> System : confirms data
    activate System

        System --> Editor : displays operation success
    deactivate System

@enduml