@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam class {
  BackgroundColor LightBlue
  BorderColor Blue
}
skinparam enum {
  BackgroundColor LightBlue
  BorderColor Blue
}
hide circle
hide methods

title Domain Model Excerpt: US04 - Create a Scenario

class Editor {
  username
  password
  createdMaps
  createdScenarios
}

class Scenario {
  nameID
  startDate
  endDate
  initialBudget
  currentBudget
}

class Map {
  nameID
  scale
}

class Industry {
  nameID
  type
  availabilityYear
  productionRate
  suppliedCargo
  demandedCargo
}

class City {
  nameID
  trafficRate
  suppliedCargo
  demandedCargo
}

class Locomotive {
  nameID
  owner
  type
  power
  acceleration
  topSpeed
  actualSpeed
  startYear
  fuelAcquisitionPrice
  fuelConsumptionPrice
  availabilityYear
  acquisitionPrice
  baseMaintenanceCost
  maintenanceFrequency
  wearAndTearFactor
}

Editor "1" -- "*" Map : creates/saves/loads >
Editor "1" -- "*" Scenario : creates/saves/loads >
Scenario "*" -- "1" Map : uses >
Map "1" -- "*" Industry : contains >
Scenario "1" -- "*" Locomotive : configures >
Scenario "1" -- "*" Industry : configures >
Map "1" -- "*" City : contains >
Scenario "1" -- "*" City : contains >

@enduml