@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

title System Sequence Diagram: US07 - List all stations and view details

actor Player
participant ListStationUI
participant ListStationController
participant Repositories
participant MapRepository
participant Map
participant City
participant Station
participant Building
participant Cargo
participant "ApplicationSession" as APP_SESSION
participant "appSession\n:ApplicationSession" as APP_SESSION_SINGLETON
participant "currentSession\n:UserSession" as CURRENT_SESSION

activate Player
Player -> ListStationUI : listStations()
activate ListStationUI
ListStationUI -> ListStationController : listAvailableMaps()
activate ListStationController

ListStationController -> APP_SESSION : getInstance()
activate APP_SESSION
APP_SESSION --> ListStationController : appSession
deactivate APP_SESSION

ListStationController -> APP_SESSION_SINGLETON : getCurrentSession()
activate APP_SESSION_SINGLETON
APP_SESSION_SINGLETON --> ListStationController : currentSession
deactivate APP_SESSION_SINGLETON

ListStationController -> CURRENT_SESSION : getCurrentEditor()
activate CURRENT_SESSION
CURRENT_SESSION --> ListStationController : currentEditor
deactivate CURRENT_SESSION

ListStationController -> Repositories : getInstance()
activate Repositories
Repositories --> ListStationController : repositories
deactivate Repositories

ListStationController -> Repositories : mapRepository()
activate Repositories
Repositories --> ListStationController : mapRepository
deactivate Repositories

ListStationController -> MapRepository : getAllMaps()
activate MapRepository
MapRepository --> ListStationController : list of maps
deactivate MapRepository

ListStationController --> ListStationUI : list of maps
deactivate ListStationController
ListStationUI -> Player : show available maps
deactivate ListStationUI

Player -> ListStationUI : selects map
activate ListStationUI
ListStationUI -> ListStationController : getStations(map)
activate ListStationController


ListStationController -> Repositories : getInstance()
activate Repositories
Repositories --> ListStationController : repositories
deactivate Repositories

ListStationController -> Repositories : mapRepository()
activate Repositories
Repositories --> ListStationController : mapRepository
deactivate Repositories

ListStationController -> MapRepository : findMap(map)
activate MapRepository
MapRepository --> ListStationController : Map
deactivate MapRepository

ListStationController -> Map : getCities()
activate Map
Map --> ListStationController : list of cities
deactivate Map

loop for each city
  ListStationController -> City : getStations()
  activate City
  City --> ListStationController : list of stations
  deactivate City
end

ListStationController --> ListStationUI : aggregated list of stations
deactivate ListStationController
ListStationUI -> Player : show station list
deactivate ListStationUI

Player -> ListStationUI : selects a station
activate ListStationUI
ListStationUI -> ListStationController : getStationDetails(stationId)
activate ListStationController
ListStationController -> Station : getDetails()
activate Station
Station --> ListStationController : name, storageCapacity, buildingSlots
deactivate Station

ListStationController -> Station : getBuildings()
activate Station
Station --> ListStationController : list of buildings
deactivate Station

ListStationController -> Station : getDemandedCargo()
activate Station
Station --> ListStationController : list of demanded cargo
deactivate Station

ListStationController -> Station : getSupplyCargo()
activate Station
Station --> ListStationController : list of supply cargo
deactivate Station

ListStationController --> ListStationUI : station details, buildings, cargo
deactivate ListStationController
ListStationUI -> Player : show station details
deactivate ListStationUI
deactivate Player

@enduml
