@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

title System Sequence Diagram : US07 - Get Available Maps

participant ListStationController
participant Repositories
participant MapRepository
participant Map

autonumber 2
--> ListStationController : getAvailableMaps()
activate ListStationController
autonumber 2.1
group GetAvailableMaps
  ListStationController -> Repositories : getInstance()
  activate Repositories
  Repositories --> ListStationController : repositoriesInstance
  deactivate Repositories

  ListStationController -> Repositories : mapRepository()
  activate Repositories
  Repositories --> ListStationController : mapRepositoryInstance
  deactivate Repositories

  ListStationController -> MapRepository : getMaps()
  activate MapRepository
  MapRepository --> ListStationController : mapsList
  deactivate MapRepository
end
autonumber 3
<-- ListStationController : availableMapsList

deactivate ListStationController

@enduml 