@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

title System Sequence Diagram : US07 - Get Station Details

participant ListStationController
participant ApplicationSession
participant Map
participant City
participant Station
participant Building
participant Cargo

activate ListStationController

autonumber 15
--> ListStationController: getStationDetails(stationId)
group GetStationDetails
    autonumber 15.1
  ListStationController -> ApplicationSession : getInstance()
  activate ApplicationSession
  ApplicationSession --> ListStationController : sessionInstance
  deactivate ApplicationSession

  ListStationController -> ApplicationSession : getCurrentMap()
  activate ApplicationSession
  ApplicationSession --> ListStationController : currentMap
  deactivate ApplicationSession

  ListStationController -> Map : getCities()
  activate Map
  Map --> ListStationController : citiesList
  deactivate Map

  ListStationController -> ListStationController : findStationById(stationId)
  activate ListStationController
  note right
    Search through each city to find
    the station with the given id
  end note
  deactivate ListStationController

  ListStationController -> Station : getDetails()
  activate Station
  Station --> ListStationController : stationBasicInfo
  deactivate Station

  ListStationController -> Station : getBuildings()
  activate Station
  Station --> ListStationController : buildingsList
  deactivate Station

  ListStationController -> Station : getDemandedCargo()
  activate Station
  Station --> ListStationController : demandedCargoList
  deactivate Station

  ListStationController -> Station : getSupplyCargo()
  activate Station
  Station --> ListStationController : supplyCargoList
  deactivate Station

  ListStationController -> ListStationController : compileStationDetails()
end

autonumber 16

<-- ListStationController: stationDetails

deactivate ListStationController

@enduml 