@startuml
title System Sequence Diagram : Ref - List Stations

participant ListStationController
participant Repositories
participant MapRepository
participant Map
participant City

activate ListStationController
group ListStations

ListStationController -> Repositories : getInstance()
activate Repositories
Repositories --> ListStationController : repositories
deactivate Repositories

ListStationController -> Repositories : mapRepository()
activate Repositories
Repositories --> ListStationController : mapRepository
deactivate Repositories

ListStationController -> MapRepository : findMap(map)
activate MapRepository
MapRepository --> ListStationController : Map
deactivate MapRepository

ListStationController -> Map : getCities()
activate Map
Map --> ListStationController : list of cities
deactivate Map

loop for each city
    ListStationController -> City : getStations()
    activate City
    City --> ListStationController : list of stations
    deactivate City
end

end
deactivate ListStationController

@enduml
