@startuml
title ref: GetStationDetails

participant ListStationController
participant Station

group GetStationDetails
activate ListStationController

ListStationController -> Station : getDetails()
activate Station
Station --> ListStationController : name, storageCapacity, buildingSlots
deactivate Station

ListStationController -> Station : getBuildings()
activate Station
Station --> ListStationController : list of buildings
deactivate Station

ListStationController -> Station : getDemandedCargo()
activate Station
Station --> ListStationController : list of demanded cargo
deactivate Station

ListStationController -> Station : getSupplyCargo()
activate Station
Station --> ListStationController : list of supply cargo
deactivate Station

deactivate ListStationController
end group

@enduml
