@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

title System Sequence Diagram: US02 - Add an industry

actor "Editor" as editor
participant ":System" as system

activate editor

    editor -> system : asks to add industry
        activate system
        system --> editor: shows all industries available in the list
        deactivate system

    editor -> system: selects industry type
        activate system
        system --> editor: requests industry data (nameID, X and Y coordinates)
        deactivate system

    editor -> system: types industry data
        activate system
        system --> editor: asks for confirmation
        deactivate system

    editor -> system: confirms industry data
        activate system
        system --> editor: displays operation success
        system --> editor: shows industry details on map
        deactivate system


@enduml