@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam class {
  BackgroundColor LightBlue
  BorderColor Blue
}
skinparam enum {
  BackgroundColor LightBlue
  BorderColor Blue
}
hide circle
hide methods

'left to right direction

class Editor {
  username
  password
  createdMaps
  createdScenarios
}

class Map {
  nameID
  scale
}

class Size {
  width
  height
}

class Position {
  x
  y
  occupied
}

class Industry {
  nameID
  type
  availabilityYear
  productionRate
  suppliedCargo
  demandedCargo
}

class IndustrySector {
  name
  importsExports
  generatesCargo
  consumesCargo
  description
}

' Relationships specific to US02 - Add Industry
Editor "1" -- "*" Map : creates/saves/loads >
Map "*" -- "1" Size : has >
Map "1" -- "*" Industry : contains >
Map "1" -- "*" Position : tracks >
Industry "1" -- "1" Position : located at >
IndustrySector "1" -- "*" Industry : contains >

@enduml