@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":BuyLocomotiveController" as CTRL
participant "scenario\n:Scenario" as SCENARIO

autonumber 3.13
-> CTRL : getAvailableLocomotives(currentScenario, currentDate)

autonumber 3.14
activate CTRL
    group Get Available Locomotives
        CTRL -> SCENARIO : getAvailableLocomotives(currentScenario, currentDate)
        activate SCENARIO
            SCENARIO --> CTRL : availableLocomotives
        deactivate SCENARIO
    end

    autonumber 4
    <-- CTRL : availableLocomotives
deactivate CTRL

@enduml 