@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":BuyLocomotiveController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "locomotiveRepository\n:LocomotiveRepository" as LOC_REPO

autonumber 12
-> CTRL : getLocomotiveDetails(locomotiveID)

autonumber 12.1

activate CTRL
    group Get Locomotive Details
        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL: repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON : getLocomotiveRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON -> CTRL : locomotiveRepository
        deactivate REPOS_SINGLETON

        CTRL -> LOC_REPO : getLocomotive(locomotiveID)
        activate LOC_REPO
            LOC_REPO --> CTRL : locomotive
        deactivate LOC_REPO

    end group

    autonumber 13
    <-- CTRL : locomotive

deactivate CTRL

@enduml 