@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class ApplicationSession
{
    - ApplicationSession()
    + {static} getInstance()
    + getCurrentSession()
}

class UserSession
{
    + getUsername()
}

class Player {
    - username : String
    - password : String
    - initialBudget : double
    - currentBudget : double
    - ownedLocomotives : List<Locomotive>
    
    + getBalance() : double
    + purchaseLocomotive(locomotive : Locomotive) : boolean
    - removeBalance(amount : double) : boolean
    - addLocomotive(locomotive : Locomotive) : boolean
}

class Locomotive {
    - nameID : String
    - type : String
    - power : double
    - acceleration : double
    - topSpeed : double
    - startYear : int
    - fuelCost : double
    - availabilityYear : int
    - acquisitionPrice : double
    - maintenancePrice : double
    - owner : Player
    - scenario : Scenario
    
    + getPrice() : double
    + getType() : String
    + getOwner() : Player
    + setOwner(player : Player) : boolean
    + getAvailableDate() : Date
    + getScenario() : Scenario
}

class Scenario {
    - nameID : String
    - timeRestrictions : String
    - technologicalRestrictions : String
    - historicalRestrictions : String
    
    + getId() : String
    + getName() : String
    + getDescription() : String
    + getStartDate() : Date
    + getEndDate() : Date
}

class LocomotiveRepository {
    + getAvailableLocomotives(scenario : Scenario, currentDate : Date) : List<Locomotive>
    + getLocomotive(locomotiveID : String) : Locomotive
    + save(locomotive : Locomotive) : boolean
}

class PlayerRepository {
    + getPlayerByUsername(username : String) : Player
    + save(player : Player) : boolean
}

class ScenarioRepository {
    + getCurrentScenario() : Scenario
}

class Repositories {
    - Repositories()
    + {static} getInstance()
    + getLocomotiveRepository() : LocomotiveRepository
    + getPlayerRepository() : PlayerRepository
    + getScenarioRepository() : ScenarioRepository
}

class BuyLocomotiveController {
    + BuyLocomotiveController()
    + getAvailableLocomotives() : List<Locomotive>
    + getLocomotiveDetails(locomotiveID : String) : Locomotive
    + purchaseLocomotive(locomotiveID : String, playerUsername : String) : boolean
    - checkBalance(locomotive : Locomotive, player : Player) : boolean
    - getPlayerByUsername(username : String) : Player
}

note right of BuyLocomotiveController
    Gets available locomotives based on
    current scenario and date
end note

note bottom of LocomotiveRepository
    - filters locomotives based on 
    scenario and availability date
end note

class BuyLocomotiveUI {
}

BuyLocomotiveUI .> BuyLocomotiveController

BuyLocomotiveController ..> ApplicationSession
BuyLocomotiveController ..> UserSession
BuyLocomotiveController ..> Locomotive
BuyLocomotiveController ..> LocomotiveRepository
BuyLocomotiveController ..> Player
BuyLocomotiveController ..> PlayerRepository
BuyLocomotiveController .> Repositories

Repositories -> "1" Repositories : instance
Repositories --> "1" LocomotiveRepository : locomotiveRepository
Repositories --> "1" PlayerRepository : playerRepository
Repositories --> "1" ScenarioRepository : scenarioRepository

ApplicationSession -> "1" ApplicationSession : instance
ApplicationSession ..> UserSession

LocomotiveRepository --> "*" Locomotive : locomotives

PlayerRepository --> "*" Player : players

Player --> "*" Locomotive : ownedLocomotives
Locomotive --> "0..1" Player : owner
Locomotive --> "1" Scenario : availableInScenario

@enduml 