@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":BuyLocomotiveController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "locomotiveRepository\n:LocomotiveRepository" as LOC_REPO

autonumber 3

 -> CTRL : getAvailableLocomotives()
autonumber 3.1
activate CTRL
    group Get Available Locomotives

            CTRL -> REPOS : getInstance()
            activate REPOS
                REPOS --> CTRL: repositories
            deactivate REPOS

            CTRL -> REPOS_SINGLETON : getLocomotiveRepository()
            activate REPOS_SINGLETON
                REPOS_SINGLETON --> CTRL: locomotiveRepository
            deactivate REPOS_SINGLETON

            CTRL -> LOC_REPO : getAvailableLocomotives(currentScenario, currentDate)
            activate LOC_REPO
                LOC_REPO --> CTRL : availableLocomotives
            deactivate LOC_REPO

    end
    autonumber 4
    <-- CTRL  : availableLocomotives
deactivate CTRL

@enduml 