@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Player" as PLAYER_ACTOR

participant ":BuyLocomotiveUI" as UI
participant ":BuyLocomotiveController" as CTRL

activate PLAYER_ACTOR

    PLAYER_ACTOR -> UI : asks to buy a locomotive

    activate UI

        UI --> CTRL** : create()
        UI -> CTRL : getAvailableLocomotives()
        ref over CTRL
            Get Available Locomotives

        end ref

        activate CTRL

            CTRL --> UI : availableLocomotives
        deactivate CTRL

        UI --> PLAYER_ACTOR : shows a list of available locomotives (for the scenario and current date)
    deactivate UI

    PLAYER_ACTOR -> UI : selects a locomotive
    activate UI

        UI -> CTRL : getLocomotiveDetails(locomotiveID)
        activate CTRL
            ref over CTRL
                Get Locomotive Details

            end ref
            CTRL --> UI : locomotive
        deactivate CTRL

        UI --> PLAYER_ACTOR : shows locomotive details and requests confirmation
    deactivate UI

    PLAYER_ACTOR -> UI : confirms purchase
    activate UI

        UI -> CTRL : purchaseLocomotive(locomotiveID)
        activate CTRL

            CTRL -> CTRL : getPlayerFromSession()
            activate CTRL

                ref over CTRL
                    Get Current Player

                end ref
                CTRL --> CTRL : player
            deactivate CTRL

            ref over CTRL
                Purchase Locomotive
            end ref

            CTRL --> UI : true
        deactivate CTRL

        UI --> PLAYER_ACTOR : displays operation success
    deactivate UI

deactivate PLAYER_ACTOR

@enduml 