@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Player" as PLAYER
participant ":MapUI" as mapUI
participant ":MapController" as mapCTRL
participant ":BuyLocomotiveUI" as UI
participant ":BuyLocomotiveController" as CTRL

activate PLAYER

    PLAYER -> mapUI: asks to see available maps
        activate mapUI
        mapUI -> mapCTRL**: create()
        mapUI -> mapCTRL: getAvailableMaps()
            activate mapCTRL
                ref over mapCTRL
                    Get available maps
                end
            mapCTRL --> mapUI: availableMapsList
            deactivate mapCTRL
        mapUI --> PLAYER: shows list of available maps to play
        deactivate mapUI

    PLAYER -> mapUI: selects a map
        activate mapUI
        mapUI -> mapCTRL: getMapScenarios(mapID)
            activate mapCTRL
                ref over mapCTRL
                    Get map scenarios
                end
            mapCTRL --> mapUI: mapScenarios
            deactivate mapCTRL
        mapUI --> PLAYER: shows list of available scenarios to play
        deactivate mapUI
    PLAYER -> mapUI: selects a scenario

        activate mapUI
        mapUI -> mapCTRL: loadMap(mapID, scenarioID)
            activate mapCTRL
                ref over mapCTRL
                    Load map
                end
            mapCTRL --> mapUI: mapLayout
            deactivate mapCTRL
        mapUI --> PLAYER: loads and displays the selected map
        deactivate mapUI


    PLAYER -> UI : asks to buy a locomotive
    activate UI
        UI --> CTRL** : create()
        UI -> CTRL : getAvailableLocomotives()
        
        ref over CTRL
            Get Current Scenario and Date
        end ref

        ref over CTRL
            Get Available Locomotives
        end ref

        activate CTRL
            CTRL --> UI : availableLocomotives
        deactivate CTRL

        UI --> PLAYER : shows a list of available locomotives (for the scenario and current date)
    deactivate UI

    PLAYER -> UI : selects a locomotive
    activate UI
        UI -> CTRL : getLocomotive(locomotiveID)
        
        ref over CTRL
            Get Locomotive
        end ref

        activate CTRL
            CTRL --> UI : locomotive
        deactivate CTRL

        UI --> PLAYER : shows locomotive details and requests confirmation
    deactivate UI

    PLAYER -> UI : confirms purchase
    activate UI
        UI -> CTRL : purchaseLocomotive(locomotive)
        
        ref over CTRL
            Get Player From Session
        end ref

        ref over CTRL
            Purchase Locomotive
        end ref

        activate CTRL
            CTRL --> UI : true
        deactivate CTRL

        UI --> PLAYER : displays operation success
    deactivate UI

deactivate PLAYER

@enduml
