@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Player" as PLAYER
participant ":BuyLocomotiveUI" as UI
participant ":BuyLocomotiveController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "locomotiveRepository\n:LocomotiveRepository" as LOC_REPO
participant "playerRepository\n:PlayerRepository" as PLAYER_REPO
participant "locomotive\n:Locomotive" as LOCOMOTIVE
participant "player\n:Player" as PLAYER_OBJ

activate PLAYER

    PLAYER -> UI : asks to buy a locomotive
    activate UI
        UI --> CTRL** : create()

        UI -> CTRL : getAvailableLocomotives()
        activate CTRL
            CTRL -> REPOS : getInstance()
            activate REPOS
                REPOS --> CTRL: repositories
            deactivate REPOS

            CTRL -> REPOS_SINGLETON : getLocomotiveRepository()
            activate REPOS_SINGLETON
                REPOS_SINGLETON --> CTRL: locomotiveRepository
            deactivate REPOS_SINGLETON

            CTRL -> LOC_REPO : getAvailableLocomotives(currentScenario, currentDate)
            activate LOC_REPO
                LOC_REPO --> CTRL : availableLocomotives
            deactivate LOC_REPO

            CTRL --> UI : availableLocomotives
        deactivate CTRL

        UI --> PLAYER : shows a list of available locomotives (for the scenario and current date)
    deactivate UI

    PLAYER -> UI : selects a locomotive
    activate UI

        UI -> CTRL : getLocomotiveDetails(locomotiveID)
        activate CTRL
            CTRL -> REPOS : getInstance()
            activate REPOS
                REPOS --> CTRL: repositories
            deactivate REPOS

            CTRL -> REPOS_SINGLETON : getLocomotiveRepository()
            activate REPOS_SINGLETON
                REPOS_SINGLETON --> CTRL: locomotiveRepository
            deactivate REPOS_SINGLETON

            CTRL -> LOC_REPO : getLocomotive(locomotiveID)
            activate LOC_REPO
                LOC_REPO --> CTRL : locomotive
            deactivate LOC_REPO

            CTRL --> UI : locomotive
        deactivate CTRL

        UI --> PLAYER : shows locomotive details and requests confirmation
    deactivate UI

    PLAYER -> UI : confirms purchase
    activate UI

        UI -> CTRL : purchaseLocomotive(locomotiveID, playerUsername)
        activate CTRL
            CTRL -> REPOS : getInstance()
            activate REPOS
                REPOS --> CTRL: repositories
            deactivate REPOS

            CTRL -> REPOS_SINGLETON : getLocomotiveRepository()
            activate REPOS_SINGLETON
                REPOS_SINGLETON --> CTRL: locomotiveRepository
            deactivate REPOS_SINGLETON

            CTRL -> LOC_REPO : getLocomotive(locomotiveID)
            activate LOC_REPO
                LOC_REPO --> CTRL : locomotive
            deactivate LOC_REPO

            CTRL -> REPOS_SINGLETON : getPlayerRepository()
            activate REPOS_SINGLETON
                REPOS_SINGLETON --> CTRL: playerRepository
            deactivate REPOS_SINGLETON

            CTRL -> PLAYER_REPO : getPlayerByUsername(playerUsername)
            activate PLAYER_REPO
                PLAYER_REPO --> CTRL : player
            deactivate PLAYER_REPO

            CTRL -> CTRL : checkBalance(locomotive, player)
            activate CTRL
                CTRL -> LOCOMOTIVE : getPrice()
                activate LOCOMOTIVE
                    LOCOMOTIVE --> CTRL : price
                deactivate LOCOMOTIVE

                CTRL -> PLAYER_OBJ : getBalance()
                activate PLAYER_OBJ
                    PLAYER_OBJ --> CTRL : balance
                deactivate PLAYER_OBJ

                CTRL --> CTRL : true
            deactivate CTRL

            CTRL -> PLAYER_OBJ : purchaseLocomotive(locomotive)
            activate PLAYER_OBJ
                PLAYER_OBJ -> PLAYER_OBJ : removeBalance(price)
                activate PLAYER_OBJ
                    PLAYER_OBJ --> PLAYER_OBJ : true
                deactivate PLAYER_OBJ

                PLAYER_OBJ -> PLAYER_OBJ : addLocomotive(locomotive)
                activate PLAYER_OBJ
                    PLAYER_OBJ --> PLAYER_OBJ : true
                deactivate PLAYER_OBJ

                PLAYER_OBJ --> CTRL : true
            deactivate PLAYER_OBJ
            
            CTRL -> LOCOMOTIVE : setOwner(player)
            activate LOCOMOTIVE
                LOCOMOTIVE --> CTRL : true
            deactivate LOCOMOTIVE

            CTRL -> LOC_REPO : save(locomotive)
            activate LOC_REPO
                LOC_REPO --> CTRL : true
            deactivate LOC_REPO

            CTRL -> PLAYER_REPO : save(player)
            activate PLAYER_REPO
                PLAYER_REPO --> CTRL : true
            deactivate PLAYER_REPO

            CTRL --> UI : true
        deactivate CTRL

        UI --> PLAYER : displays operation success
    deactivate UI

deactivate PLAYER

@enduml