@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

title System Sequence Diagram : US03 - Add a City

actor Editor
participant ":AddCityUI" as UI
participant ":AddCityController" as Controller
participant ":CityDTO" as CityDTO

activate Editor

Editor -> UI : asks to add a city
activate UI
UI -> Controller : create()
activate Controller

UI -> Controller : getListOfMaps()
ref over Controller
    Get MapDTO List
end
Controller --> UI : list<MapDTO>
deactivate Controller

UI --> Editor : shows map list and asks to select one
deactivate UI

Editor -> UI : selects a map
activate UI
UI -> Editor : asks for city name, coordinates, and number of house blocks
deactivate UI

Editor -> UI : types requested data
activate UI

UI -> CityDTO : createCityDTO(name, coordinates, numBlocks)

UI --> Editor : ask if blocks are assigned manually
deactivate UI

Editor -> UI : selects yes/no
activate UI

alt User selects "manual"
    loop for each block (i in 1..numBlocks)
        UI --> Editor : ask coordinates for block i
        Editor -> UI : inputs coordinates
        UI -> Controller : createHouseBlockDTO(map, coordinates)
        ref over Controller
            Create HouseBlockDTO
        end
        activate Controller
        Controller --> UI : houseBlockDTO
        deactivate Controller
        UI -> CityDTO : addHouseBlock(houseBlockDTO)
    end

else User selects "automatic"
    UI -> Controller : createListHouseBlocksDTO(numBlocks)
    activate Controller
    ref over Controller
        CreateListAutoBlocksDTO
    end
    Controller --> UI : list<HouseBlockDTO>
    deactivate Controller
    UI -> CityDTO : addHouseBlocksList(houseBlocksListDTO)
end

UI --> Editor : asks for confirmation
Editor -> UI : confirms

UI -> Controller : saveCity(mapDTO, cityDTO)
activate Controller
ref over Controller
    Save City
end
Controller --> UI : CityDTO
deactivate Controller

UI --> Editor : shows city details and success message
deactivate UI

@enduml
