@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
title Class Diagram - Create City & Assign HouseBlocks

class AddCityUI {
}

class AddCityController {
    +createCity(cityDTO: CityDTO)
    +getListOfMaps(): List<MapDTO>
    +createHouseBlockDTO(mapDTO: MapDTO, coordinate: Position): HouseBlockDTO
    +createListOfHouseBlocksDTO(numHouseBlocks: int): List<HouseBlockDTO>
    +saveCity(cityDTO: CityDTO, mapDTO: MapDTO)
}

class MapRepository {
  +getListOfMaps(): List<Map>
    +getMap(mapID: String): Map
}

class Repositories {
  +getInstance(): Repositories
  +getMapRepository(): MapRepository
}

class Maps {
  +getListOfMaps(): List<Map>
  +getMap(mapID: String): Map
}

class MapMapper {
  +toDTO(map: Map): MapDTO
  +toModel(mapDTO: MapDTO): Map
}

class Map {
  -cities: Cities
  -positions: List<Position>
  +createCity(cityDTO: CityDTO)
  +getCityBoundaries(): List<Position>
  +getAvailablePositions(n: int): List<Position>
  +markPositionOccupied(pos: Position)
}

class Cities {
  +addCity(city: City)
  +validateCity(city: City): boolean
}

class City {
  -nameID: String
  -position: Position
  -houseBlocks: List<HouseBlock>
    +create(nameID: String, position: Position)
    +addHouseBlock(houseBlock: HouseBlock)
    +setHouseBlocks(houseBlocks: List<HouseBlock>)
}

class HouseBlock {
  -position: Position
  -autoAssigned: boolean
}

class HouseBlockDTO {
  +position: Position
  +autoAssigned: boolean

  +getPosition(): Position
    +isAutomaticPlacement(): boolean

}

class Position {
  -x: int
  -y: int
  -occupied: boolean
  +setOccupied(val: boolean)
}

class CityMapper {
  +toModel(cityDTO: CityDTO): City
    +toDTO(city: City): CityDTO
}

class CityDTO {
  +nameID: String
  +position: Position
    +houseBlockDTOs: List<HouseBlockDTO>

  getNameID(): String
    getPosition(): Position
    getHouseBlocksDTO(): List<HouseBlockDTO>
}

class MapDTO {
  +id: String
}

' RELATIONSHIPS
AddCityUI --> AddCityController
AddCityController --> Repositories
AddCityController --> MapMapper
MapMapper --> MapDTO
MapRepository -> MapMapper
Repositories --> MapRepository
MapRepository --> Maps
Maps --> Map
Map --> Cities
Cities --> City
Cities --> CityMapper
CityMapper --> CityDTO
CityMapper --> HouseBlockDTO
City --> HouseBlock
HouseBlock --> Position
CityDTO --> Position
AddCityController --> CityMapper

@enduml
