@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber 22

participant ":AddIndustryController" as CTRL
participant "MapRepository" as REPOS_MAP
participant "Map" as MAP
participant "Industry" as IND

    -> CTRL: createIndustry(nameID, x, y)
    activate CTRL
    group Create and add industry to map

    autonumber 22.1

    CTRL -> IND: create(nameID, x, y)
        activate IND
            IND --> CTRL: newIndustry
        deactivate IND

        CTRL -> MAP: addIndustry(newIndustry)
        activate MAP
            MAP --> CTRL: success
        deactivate MAP

        CTRL -> REPOS_MAP: save(currentMap)
        activate REPOS_MAP
            REPOS_MAP --> CTRL: success
        deactivate REPOS_MAP
        end
        autonumber 23
       <-- CTRL: industryDetails

    deactivate CTRL

@enduml