@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

class Editor {
    name
    createdMaps
    createdScenarios
}

class Player {
    name
    currentGame
}

class Map{
    name
    width
    height
    cities
}

class Scenario{
    name
    maps
    restrictions
    startDate
    endDate
}

class Restriction{
    restrictionType
}

class City{
    name
    width
    height
    population
    stations
    industries
}

class Industry{
    name
    width
    height
}

class PrimaryIndustry{
    generatedResources
}

class TransformingIndustry{
    transformedResources
}

class Resource{
    name
    cargoType
}

class Station{
    name
    stationType
    width
    height
    routes
    connectedRailways
}

class RailwayLine{
    stations
    railway
}

class Railway{
    name
    stations
    routes
    railwayLines
}

class Route{
    name
    stations
    trains
}

class Train{
    locomotives
    carriage
    routes
    currentRoute
}

class Locomotive{
    locomotiveType
}

class Carriage{
    cargoType
}

enum RestrictionType{
    timeRestrictions
    technologyRestrictions
    historicalRestrictions
}

enum StationType{
    depot
    station
    terminal
}

enum LocomotiveType{
    steam
    diesel
    electricity
}

enum CargoType{
    passengers
    mail
    coal
    iron ore
    steel
    cars
    food
    textiles
}

Editor "1" -- "0..*" Map: create/edit
Editor "1" -- "0..*" Scenario: create/edit
Player "1" -- "0..*" Scenario: play
Scenario "1..*" -- "1..*" Restriction: has
Restriction "1..*" -- "1" RestrictionType: has
Map "1..*" -- "1..*" City: has
Map "1" -- "0..*" Scenario: has
City "1" -- "1..*" Station: has
City "1" -- "1..*" Industry: has
Station "1" -- "0..*" Industry: serves
Station "1..*" -- "1" StationType: has
Station "2" -- "1..*" RailwayLine: has
Station "1..*" -- "1" Railway: has
RailwayLine "1..*" -- "1" Railway: has
Station "1..*" -- "1..*" Route: has
Railway "1" -- "1..*" Route: has
Route "1..*" -- "1..*" Train: has
Train "1" -- "1..*" Locomotive: has
Train "1" -- "0..*" Carriage: has
Locomotive "1..*" -- "1" LocomotiveType: has
Carriage "1..*" -- "1" CargoType: has
Industry <|-- PrimaryIndustry
Industry <|-- TransformingIndustry
PrimaryIndustry "1..*" -- "1..*" Resource: generates
TransformingIndustry "1..*" -- "1..*" Resource: transforms
Resource "1..*" -- "1" CargoType: has

@enduml