@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam class {
  BackgroundColor LightBlue
  BorderColor Blue
}
skinparam enum {
  BackgroundColor LightBlue
  BorderColor Blue
}
hide circle
hide methods

class Player {
  username
  password
  initialBudget
  currentBudget
  ownedLocomotives
}

class Editor {
  username
  password
  createdMaps
  createdScenarios
}

class Map {
  nameID
}

class Size {
  width
  height
}

class Position {
  x
  y
  occupied
}

class Scenario {
  nameID
  timeRestrictions
  technologicalRestrictions
  historicalRestrictions
}

class Simulator {
  status
  runTime
  report
}

class SimulationReport {
    startDate
    endDate
    simulationDuration
    totalRevenue
    totalExpenses
    totalProfits
    hitBankruptcy
}



class City {
  nameID
  productionRate
  suppliedCargo
  demandedCargo
}

class HouseBlock {
  automaticPlacement
}

class Industry {
  nameID
  type
  availabilityYear
  productionRate
  suppliedCargo
  demandedCargo
}

class IndustrySector {
  name
  importsExports
  generatesCargo
  consumesCargo
  description
}

class Cargo {
  name
  amount
  lifespan
  type
}

class Station {
  nameID
  storageCapacity
  buildingSlots
  availableCargo
  requestedCargo
}

class StationType {
  name
  economicRadius
  cost
  centerPoint
}

class TrainSchedule {
  expectedArrivalTime
  expectedDepartureTime
  actualArrivalTime
  actualDepartureTime
}

class Building {
  nameID
  type
  availabilityYear
  evolutionCost
  evolutionStagesLeft
}

class RailwayLine {
  length
  trackType
  isElectrified
  cost
}

class RailwayNetwork{
    nameID
    routeList
    }

class Locomotive {
  nameID
  owner
  type
  power
  acceleration
  topSpeed
  startYear
  fuelCost
  availabilityYear
  acquisitionPrice
  maintenancePrice
}

class Train {
  nameID
}

class Carriage {
  storageCapacity
}

class Route {
  nameID
  stationSequence
  cargoList
}

' Relationships
Editor "1" -- "*" Map : creates >
Editor "1" -- "*" Scenario : creates >
Scenario "*" -- "1" Map : uses >
Player "1" -- "*" Scenario : plays >
Scenario "*" -- "1" Simulator : runs in >
Map "1" -- "*" City : contains >
Map "1" -- "*" Industry : contains >
Map "*" -- "1" Size : has >
City "*" -- "*" Cargo : produces/consumes >
Player "1" -- "*" Station : builds >
Player "1" -- "*" RailwayLine : builds >
Station "1" -- "*" Building : upgraded with >
Station "1" -- "*" City : serves >
Station "1" -- "*" Industry : serves >
Station "1" -- "*" Cargo : stores >
RailwayLine "1" -- "2" Station : connects >
Player "1" -- "*" Locomotive : buys >
Train "1" -- "1" Locomotive : powered by >
Train "1" -- "*" Carriage : composed of >
Carriage "*" -- "1" Cargo : carries >
Train "1" -- "*" Route : assigned to >
Route "1" -- "*" Station : includes >
Route "*" -- "*" Cargo : manages >
Scenario "1" -- "*" Locomotive : configures >
Scenario "1" -- "*" Industry : configures >
Scenario "1" -- "*" IndustrySector : configures >
Scenario "1" -- "*" Station : configures >
Route "1..*" -- "1..*" RailwayLine : contains >
Building "1" -- "0..1" Building : evolves into >
Player "1" -- "*" Route : defines >
Simulator "1" --> "*" Cargo : generates >
Scenario "1" -- "*" City : configures >
City "1" -- "1" Position : located at >
Industry "1" -- "1" Position : located at >
Station "1" -- "1" Position : located at >
Map "1" -- "*" Position : contains >
City "1" -- "1..*" HouseBlock : contains >
HouseBlock "1" -- "1" Position : has >
IndustrySector "1" -- "*" Industry : contains >
Industry "*" -- "*" Cargo : produces/consumes >
Station "*" -- "1" StationType : defined by >
StationType "1" -- "*" StationType : can change >
TrainSchedule "*" -- "*" Train: contains >
Station "*" -- "1" TrainSchedule: generates >
RailwayNetwork "1" -- "*" RailwayLine : contains >
Simulator "1" -- "*" SimulationReport : generates >
SimulationReport "*" -- "1" Scenario : reports a >
SimulationReport "*" -- "1" Player : belongs to >
@enduml
