@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam class {
  BackgroundColor LightBlue
  BorderColor Blue
}
skinparam enum {
  BackgroundColor LightBlue
  BorderColor Blue
}
hide circle
hide methods

class Player {
  username
  password
  ownedLocomotives
}

class Editor {
  username
  password
  createdMaps
  createdScenarios
}

class Map {
  nameID
  scale
}

class Size {
  width
  height
}

class Position {
  x
  y
  occupied
}

class Scenario {
  nameID
  startDate
  endDate
  initialBudget
  currentBudget
}

class Simulator {
  status
  runTime
  report
}

class CargoGenerationEvent {
  eventID
  timestamp
  cargoUsed
  generatedCargo
  amount
  genesisSource
  storageStation
  cargoType
  creationTime
  status
}

class DepartureEvent {
    eventID
    timestamp
    status
    nextStation
    loadedCargo
}

class ArrivalEvent {
    eventID
    timestamp
    status
    previousStation
    traveledDistance
    duration
    revenue
    fuelExpenses
}

class SimulationReport {
    startDate
    endDate
    simulationDuration
    totalRevenue
    totalExpenses
    totalProfits
    hitBankruptcy
}

class City {
  nameID
  trafficRate
  suppliedCargo
  demandedCargo
}

class HouseBlock {
  automaticPlacement
}

class Industry {
  nameID
  type
  availabilityYear
  productionRate
  suppliedCargo
  demandedCargo
}

class IndustrySector {
  name
  importsExports
  generatesCargo
  consumesCargo
  description
}

class Cargo {
  name
  amount
  lifespan
  type
  pricePerUnit
}

class Station {
  nameID
  storageCapacity
  buildingSlots
  availableCargo
  requestedCargo
}

class StationType {
  name
  economicRadius
  cost
  centerPoint
}

class TrainSchedule {
  calculatedArrivalTime
  calculatedDepartureTime
  actualArrivalTime
  actualDepartureTime
  departureStation
  arrivalStation
}

class Building {
  nameID
  type
  availabilityYear
  evolutionCost
  evolutionStagesLeft
  effect
}

class RailwayLine {
  length
  placementPrice
  maintenanceCostPerKm
  wearAndTearFactor
}

class TrackType{
  typeName
  speedDegradation
  isElectrified
}

class Locomotive {
  nameID
  owner
  type
  power
  acceleration
  topSpeed
  actualSpeed
  startYear
  fuelAcquisitionPrice
  fuelConsumptionPrice
  availabilityYear
  acquisitionPrice
  baseMaintenanceCost
  maintenanceFrequency
  wearAndTearFactor 
}

class Train {
  nameID
  traveledKms
  status
}

class Carriage {
  carriageID
  storageCapacity
  status
  speedDegradation
}

class Route {
  nameID
  stationSequence
}

class PointOfRoute {
  cargoMode
}

' Relationships
Editor "1" -- "*" Map : creates/saves/loads >
Editor "1" -- "*" Scenario : creates/saves/loads >
Scenario "*" -- "1" Map : uses >
Player "1" -- "*" Scenario : plays >
Scenario "*" -- "1" Simulator : runs in >
Map "1" -- "*" City : contains >
Map "1" -- "*" Industry : contains >
Map "*" -- "1" Size : has >
City "*" -- "*" Cargo : produces/consumes >
Player "1" -- "*" Station : builds >
Player "1" -- "*" RailwayLine : builds >
Station "1" -- "*" Building : upgraded with >
Station "1" -- "*" City : serves >
Station "1" -- "*" Industry : serves >
Station "1" -- "*" Cargo : stores >
RailwayLine "1" -- "2" Station : connects >
Player "1" -- "*" Locomotive : buys >
Train "1" -- "1" Locomotive : powered by >
Train "1" -- "*" Carriage : composed of >
Carriage "*" -- "1" Cargo : loads >
Train "1" -- "1" Route : assigned to >
Route "1" -- "*" PointOfRoute : contains >
PointOfRoute "1" -- "1" Station : represents >
PointOfRoute "*" -- "*" Cargo : stores >
Route "*" -- "*" Cargo : manages >
Scenario "1" -- "*" Locomotive : configures >
Scenario "1" -- "*" Industry : configures >
Scenario "1" -- "*" IndustrySector : configures >
Scenario "1" -- "*" Station : configures >
Route "1..*" -- "1..*" RailwayLine : contains >
Building "1" -- "0..1" Building : evolves into >
Player "1" -- "*" Route : defines >
Scenario "1" -- "*" City : configures >
City "1" -- "1" Position : located at >
Industry "1" -- "1" Position : located at >
Station "1" -- "1" Position : located at >
Map "1" -- "*" Position : tracks >
City "1" -- "1..*" HouseBlock : contains >
HouseBlock "1" -- "1" Position : has >
IndustrySector "1" -- "*" Industry : contains >
Industry "*" -- "*" Cargo : produces/consumes >
Station "*" -- "1" StationType : defined by >
StationType "1" -- "*" StationType : can change >
TrainSchedule "*" -- "*" Train: belongs to >
Station "1" -- "*" TrainSchedule: generates >
Simulator "1" -- "*" SimulationReport : generates >
SimulationReport "*" -- "1" Scenario : reports a >
SimulationReport "*" -- "1" Player : belongs to >
RailwayLine "*" -- "1" TrackType: has
Simulator "1" -- "*" CargoGenerationEvent : handles >
CargoGenerationEvent "*" -- "1" Cargo : generates >
Simulator "1" -- "*" DepartureEvent : handles >
Simulator "1" -- "*" ArrivalEvent : handles >

Cargo "*" -- "*" Cargo : uses >
Route "1" -- "*" TrainSchedule : stores  >


DepartureEvent "*" -- "1" Train : involves >

DepartureEvent "*" -- "1" Station : occurs at >
DepartureEvent "*" -- "*" Cargo : loads >

ArrivalEvent "*" -- "1" Train : involves >

ArrivalEvent "*" -- "1" Station : occurs at >
ArrivalEvent "*" -- "*" Cargo : unloads/discards >
ArrivalEvent "*" -- "1" CargoGenerationEvent : triggers >

@enduml
