@startuml
skinparam classBackgroundColor #ADD8E6
skinparam linetype polyline
skinparam ClassAttributeIconSize 5000
skinparam ranksep 50

hide circle
hide methods

title Railway Network Simulation - Domain Model

class User {
    email
    password
}

class Player{
}

class Editor{

}
class Map{
    name
    size
}
class Scenario{
    Time Restrictions
    Technological Restrictions
    Historical Restrictions
}
class Simulator {
    start
    finish
    run Time
    items report
}
class Industry{
}
class PrimaryInd{}
class TranformingInd{}
class MixedInd{}
class CoalMine{}
class Coal{}
class Food{}
class Bakery{}
class City{
    name
    location
    housing
}
class Mail{}
class Passengers{}
class Port{}
class Cargo{
    Quantity
    Type
}
class Station{
    name
    price
    radius
    }
class Type_Deposts{
    price = 50k
    radius = 3x3
}
class Type_Terminals {
    price = 100k
    radius = 4x4
}
class Type_Station {
    price = 200k
    radius = 5x5
}
class Building{
}
class Railway{
    length
    linetype
}
class Train{
    name
    velocity
}
class Line {
}

class Locomotive{}
class Carriage {}
class Type_Single
class Type_Double
class Type_Electrified
class Run_Steam{}
class Run_Diesel{}
class Run_Electricity{}

class RoutePoint{
    sequence
}


Player --> Simulator : plays
Editor --> Scenario : creates
Editor --> Map : creates
Industry --> Cargo : uses
CoalMine --> Coal : generates
Bakery --> Food : transforms
Station --> Cargo :  transports
Industry --> Station : demand / receave suply
City --> Station : demand /receave suply
City --> Passengers : produces
City --> Mail : produces


'significa se o scenario morrer o mapa tbm morre
Scenario"1..*" *-- "1"Map
Map "1"*-- "0..*"City
Map "1"*-- "0..*"Industry
MixedInd *-- Port
Station"1" *--"1..*" Building
Train "1" *-- "1..2" Locomotive
Simulator *-- Scenario
Railway *-- Line : is composed by
Station"1" --*"1..*" Railway : is composed
Train "1" --> "*" RoutePoint : Route

Train "1" o-- Carriage
MixedInd o-- TranformingInd
MixedInd o-- Station
RoutePoint o-- Cargo

User <|-- Editor
User <|-- Player
Industry <|-- PrimaryInd
Industry <|-- TranformingInd
Bakery --|> TranformingInd
PrimaryInd <|-- CoalMine
Coal --|> Cargo
Food --|> Cargo
Mail --|> Cargo
Passengers --|> Cargo
Cargo --|> Carriage
Station <|-- Type_Deposts
Station <|-- Type_Station
Station <|-- Type_Terminals
Line <|-- Type_Double
Line <|-- Type_Single
Line <|-- Type_Electrified
Locomotive <|-- Run_Steam
Locomotive <|-- Run_Diesel
Locomotive <|-- Run_Electricity



@enduml