@startuml

@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam class {
  BackgroundColor LightBlue
  BorderColor Blue
}
skinparam enum {
  BackgroundColor LightBlue
  BorderColor Blue
}
hide circle
hide methods

left to right direction

title Domain Model Excerpt: US14 - Railway Lines Maintenance Route

class Player {
  username
}

class Station {
  nameID
  position
}

class RailwayLine {
  length
  isElectrified
}

class RailwayNetwork {
  nameID
}

class MaintenanceRoute {
  startStation
  routeSequence
}

class MaintenanceType {
  name
  description
}

' Relationships
RailwayNetwork "1" -- "*" RailwayLine : contains >
RailwayLine "1" -- "2" Station : connects >
Player "1" -- "*" MaintenanceRoute : requests >
MaintenanceRoute "1" -- "1" MaintenanceType : follows >
MaintenanceRoute "1" -- "*" RailwayLine : includes >
MaintenanceRoute "1" -- "*" Station : passes through >

@enduml