@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

title System Sequence Diagram : US03 - Add a city

actor "Editor" as Editor
participant ":System" as AddCityUI

activate Editor
Editor -> AddCityUI : asks to edit map
        activate AddCityUI
            AddCityUI --> Editor: shows list of available maps
        deactivate AddCityUI

    Editor -> AddCityUI: selects a map
        activate AddCityUI
            AddCityUI --> Editor: loads and displays the selected map
        deactivate AddCityUI

Editor -> AddCityUI : asks to add city
        activate AddCityUI

        AddCityUI --> Editor : requests city data (nameID, X and Y coordinates, number of house blocks)
        deactivate AddCityUI

        Editor --> AddCityUI : types city data
    activate AddCityUI
        AddCityUI --> Editor: asks if the editor wants to assign the blocks manually or automatically
        deactivate AddCityUI
    Editor -> AddCityUI: selects yes/no
        activate AddCityUI
        AddCityUI --> AddCityUI: assign blocks
        AddCityUI --> Editor: asks for confirmation
        deactivate AddCityUI
        Editor -> AddCityUI: confirms city data

        activate AddCityUI
        AddCityUI --> Editor: displays operation success
        AddCityUI --> Editor: display city details
        deactivate AddCityUI


@enduml