@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Player" as Player
participant ":System" as System

activate Player

    Player -> System : asks to verify train travel between stations
    activate System

        System --> Player : shows available train types (steam, diesel, electric)\nand requests selection
    deactivate System

    Player -> System : selects train type
    activate System

        System --> Player : displays network visualization with stations and lines\n(electrified lines in different color)
    deactivate System

    Player -> System : selects origin station
    activate System

        System --> Player : requests destination station selection
    deactivate System

    Player -> System : selects destination station
    activate System

        System --> Player : displays if the selected train can travel\nbetween the chosen stations
    deactivate System

@enduml
