@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

title System Sequence Diagram: Confirm and Save City

actor Editor
participant AddCityUI
participant AddCityController
participant Reporitories
participant MapRepository
participant Map
participant City

activate Editor
AddCityUI -> Editor : asks for confirmation
deactivate AddCityUI
Editor -> AddCityUI : confirms

activate AddCityUI
AddCityUI -> AddCityController : saveCity(name, coordinates, houseBlocks)
activate AddCityController
AddCityController -> City : create(name, coordinates, houseBlocks)
activate City
City --> AddCityController : cityObject
deactivate City
AddCityController -> Map : addCity(city)
activate Map
Map --> AddCityController : true
deactivate Map

' Add saving to repository
AddCityController -> Repositories : getInstance()
activate Repositories
Repositories --> AddCityController : repositories
deactivate Repositories
AddCityController -> Repositories : mapRepository()
activate Repositories
Repositories --> AddCityController : mapRepository
deactivate Repositories
AddCityController -> MapRepository : saveMap(map)
activate MapRepository
MapRepository --> AddCityController : true
deactivate MapRepository

AddCityController --> AddCityUI : true
deactivate AddCityController

AddCityUI -> Editor : operation success
deactivate AddCityUI
deactivate Editor

@enduml