@startuml US03-SSD-AssignBlocks

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

title System Sequence Diagram: Assign House Blocks

actor Editor
participant AddCityUI
participant AddHouseBlocksController
participant HouseBlock
participant City

activate Editor
AddCityUI -> Editor : ask if assign blocks manually
deactivate AddCityUI
Editor -> AddCityUI : selects yes/no
activate AddCityUI
AddCityUI -> AddHouseBlocksController : assignBlocks(manual/auto, numBlocks, map, cityCoordinates)
activate AddHouseBlocksController

loop for each block
AddHouseBlocksController -> HouseBlock : setHouseBlockCoordinate()
activate HouseBlock
HouseBlock --> AddHouseBlocksController : true
deactivate HouseBlock
end

AddHouseBlocksController -> City : addBlocks()
activate City
City --> AddHouseBlocksController : true
deactivate City
AddHouseBlocksController --> AddCityUI : true
deactivate AddHouseBlocksController
deactivate AddCityUI
deactivate Editor

@enduml
