@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

actor Editor
participant AddCityUI
participant AddCityController
participant Repositories
participant MapRepository
participant AddHouseBlocksController
participant City
participant Map
participant HouseBlock

activate Editor
Editor -> AddCityUI : asks to add a city
activate AddCityUI
AddCityUI -> AddCityController : create()
activate AddCityController
AddCityUI -> AddCityController : getAvailableMaps()
AddCityController -> Repositories : getInstance()
activate Repositories
Repositories -> MapRepository : mapRepository()
activate MapRepository
MapRepository -> AddCityController : getAvailableMaps()
deactivate MapRepository
deactivate Repositories
AddCityController -> AddCityUI : availableMaps
deactivate AddCityController
AddCityUI -> Editor : shows a list of maps
deactivate AddCityUI

Editor -> AddCityUI : selects a map
activate AddCityUI

AddCityUI -> Editor : asks for city name
deactivate AddCityUI
Editor -> AddCityUI : inputs name
activate AddCityUI
AddCityUI -> AddCityController : validateName(name)
activate AddCityController
AddCityController -> AddCityController : checkNoDigitsOrSpecialChars()
AddCityController --> AddCityUI : true
deactivate AddCityController

AddCityUI -> Editor : asks for coordinates
deactivate AddCityUI
Editor -> AddCityUI : inputs coordinates
activate AddCityUI
AddCityUI -> AddCityController : validateCoordinates(coordinates)
activate AddCityController
AddCityController --> AddCityUI : true
deactivate AddCityController
AddCityUI -> Editor : asks number of house blocks
deactivate AddCityUI
Editor -> AddCityUI : inputs number
activate AddCityUI
AddCityUI -> AddCityController : validateNumberPositive()
activate AddCityController
AddCityController --> AddCityUI : true
deactivate AddCityController

AddCityUI -> Editor : ask if assign blocks manually
deactivate AddCityUI
Editor -> AddCityUI : selects yes/no
activate AddCityUI
AddCityUI -> AddHouseBlocksController : assignBlocks(manual/auto, numBlocks, map, cityCoordinates)
activate AddHouseBlocksController
AddHouseBlocksController -> HouseBlock : setHouseBlockCoordinate()
activate HouseBlock
HouseBlock --> AddHouseBlocksController : true
deactivate HouseBlock
AddHouseBlocksController -> City : addBlocks()
activate City
City --> AddHouseBlocksController : true
deactivate City
AddHouseBlocksController --> AddCityUI : true
deactivate AddHouseBlocksController

AddCityUI -> AddCityController : saveCity(name, coordinates)
activate AddCityController
AddCityController -> City : create(name, coordinates)
activate City
City --> AddCityController : cityObject
deactivate City
AddCityController -> Map : addCity(city)
activate Map
Map --> AddCityController : true
deactivate Map
AddCityController --> AddCityUI : true
deactivate AddCityController

AddCityUI -> Editor : operation success
deactivate AddCityUI
deactivate Editor

@enduml
