@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber 12

participant ":AssignTrainController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "routeRepository\n:RouteRepository" as REPOS_ROUTE

-> CTRL: getAvailableRoutes()
activate CTRL
autonumber 12.1
group Get available routes
    CTRL -> REPOS: getInstance()
        activate REPOS
            REPOS --> CTRL: repositories
        deactivate REPOS

    CTRL -> REPOS_SINGLETON: getRouteRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL: routeRepository
        deactivate REPOS_SINGLETON

    CTRL -> REPOS_ROUTE: getAvailableRoutes()
        activate REPOS_ROUTE
            REPOS_ROUTE --> CTRL: availableRoutesList
        deactivate REPOS_ROUTE
end
autonumber 13

<-- CTRL: availableRoutesList

deactivate CTRL

@enduml 