@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber 16

participant ":AssignTrainController" as CTRL
participant "routeRepository\n:RouteRepository" as REPOS_ROUTE
participant "route\n:Route" as ROUTE

-> CTRL: getRouteDetails(selectedRoute)
activate CTRL
autonumber 16.1
group Get route details
    CTRL -> REPOS_ROUTE: getRoute(selectedRoute)
        activate REPOS_ROUTE
            REPOS_ROUTE --> CTRL: route
        deactivate REPOS_ROUTE

    CTRL -> ROUTE: getRouteDetails()
        activate ROUTE
            ROUTE --> CTRL: routeDetails
        deactivate ROUTE
end
autonumber 17

<-- CTRL: routeDetails

deactivate CTRL

@enduml 