@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber 25

participant ":AssignTrainController" as CTRL
participant "trainRepository\n:TrainRepository" as REPOS_TRAIN
participant "train\n:Train" as TRAIN

-> CTRL: getTrainDetails(selectedTrain)
activate CTRL
autonumber 25.1
group Get train details
    CTRL -> REPOS_TRAIN: getTrain(selectedTrain)
        activate REPOS_TRAIN
            REPOS_TRAIN --> CTRL: train
        deactivate REPOS_TRAIN

    CTRL -> TRAIN: getTrainDetails()
        activate TRAIN
            TRAIN --> CTRL: trainDetails
        deactivate TRAIN
end
autonumber 26

<-- CTRL: trainDetails

deactivate CTRL

@enduml 