@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'hide footbox
participant ":MapController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "mapRepository\n:MapRepository" as MAP_REPO
participant "map\n:Map" as MAP

autonumber 11
-> CTRL: loadMap(mapID, scenarioID)

autonumber 11.1
activate CTRL
    group Load Map
        CTRL -> REPOS: getInstance()
        activate REPOS
            REPOS --> CTRL: repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON: getMapRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL: mapRepository
        deactivate REPOS_SINGLETON

        CTRL -> MAP_REPO: getMap(mapID)
        activate MAP_REPO
            MAP_REPO --> CTRL: map
        deactivate MAP_REPO

        CTRL -> MAP: getMapLayout(scenarioID)
        activate MAP
            MAP --> CTRL: mapLayout
        deactivate MAP
    end

autonumber 12
    <-- CTRL: mapLayout
deactivate CTRL


@enduml