@startuml
autonumber
title "System Sequence Diagram - US23 : Save Game Progress"
actor "Player" as Player
participant ":System" as System

activate Player

Player -> System: requests to save current game progress
activate System
System --> Player: displays current game state (budget, time, etc.)
System --> Player: request save confirmation
deactivate System

Player -> System: confirms save operation
activate System
System --> Player: displays operation success
System --> Player: displays saved game details (timestamp, progress, etc.)
deactivate System

@enduml
