@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

title System Sequence Diagram: US06 - Upgrade a selected station with a building

actor "Player" as player
participant ":System" as system

activate player
player -> system : Asks to upgrade a station
activate system
system --> player : Shows the list of available stations
deactivate system

player -> system : Selects a station
activate system
system --> player : Loads and displays the selected station details
deactivate system

player -> system : Confirms the selected station
activate system
system --> player : Shows the list of available buildings for upgrade
deactivate system

player -> system : Selects a building
activate system
system --> player : Shows building details and asks for confirmation
deactivate system

player -> system : Confirms the upgrade
activate system
system --> player : Displays success message
deactivate system

deactivate player
@enduml
