@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Player" as Player
participant ":System" as System

activate Player

    Player -> System : asks to buy a locomotive
    activate System

        System --> Player : asks for the current date
    deactivate System

    Player -> System : types the current date
    activate System

        System --> Player : shows a list of available locomotives
    deactivate System

    Player -> System : selects a locomotive
    activate System

        System --> Player : shows locomotive details, and requests confirmation
    deactivate System

    Player -> System : confirms purchase
    activate System

        System -> System : verifies player budget
        System --> Player : displays operation success
    deactivate System

deactivate Player
@enduml
