@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateScenarioController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "mapDTO\n:MapDTO" as MAP_DTO
participant "mapRepository\n:MapRepository" as MAP_REPO
participant "maps\n:Maps" as MAPS
participant "map\n:Map" as MAP
participant "scenarios:Scenarios" as SCNS
participant ":ScenarioMapper" as SCN_MAPPER
participant "scenarioDTO\n:ScenarioDTO" as SCN_DTO
participant "scenario:Scenario" as SCN


autonumber 22
-> CTRL: createScenario(mapDTO, scenarioDTO)

autonumber 22.1
activate CTRL
    group Create Scenario Object

        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL: repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON: getMapRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL: mapRepository
        deactivate REPOS_SINGLETON

        CTRL -> MAP_DTO: getListOfCityDTO()
        activate MAP_DTO

            MAP_DTO --> CTRL: listCityDTO
        deactivate MAP_DTO

        CTRL -> SCN_DTO: addCities(listCityDTO)
        activate SCN_DTO
            deactivate SCN_DTO

        CTRL -> MAP_DTO: getNameID()
        activate MAP_DTO
            MAP_DTO --> CTRL: mapNameID
        deactivate MAP_DTO

        CTRL -> MAP_REPO: createScenario(scenarioDTO, mapNameID)
            activate MAP_REPO

            MAP_REPO -> MAPS: createScenario(scenarioDTO, mapNameID)
            activate MAPS

            MAPS -> MAP: createScenario(scenarioDTO, mapNameID)
            activate MAP

            MAP -> SCNS: createScenario(scenarioDTO)
            activate SCNS

            SCNS -> SCN_MAPPER: scenario = toModel(scenarioDTO)
                activate SCN_MAPPER

                SCN_MAPPER -> SCN_DTO: nameID = getNameID()
                activate SCN_DTO
                deactivate SCN_DTO

                SCN_MAPPER -> SCN_DTO: startDate = getStartDate()
                activate SCN_DTO
                deactivate SCN_DTO

                SCN_MAPPER -> SCN_DTO: endDate = getEndDate()
                activate SCN_DTO
                deactivate SCN_DTO

                SCN_MAPPER -> SCN_DTO: initialBudget = getInitialBudget()
                activate SCN_DTO
                deactivate SCN_DTO

                SCN_MAPPER -> SCN_DTO: industries = getIndustries()
                activate SCN_DTO
                deactivate SCN_DTO

                SCN_MAPPER -> SCN_DTO: cities = getCities()
                activate SCN_DTO
                deactivate SCN_DTO

                SCN_MAPPER -> SCN_DTO: locomotiveTypes = getLocomotiveTypes()
                activate SCN_DTO
                deactivate SCN_DTO

                SCN_MAPPER -> SCN**: create(nameID, startDate, endDate, initialBudget,\nindustries, cities, locomotiveTypes)
                deactivate SCN_MAPPER

                SCNS -> SCNS: addScenario(scenario)
                activate SCNS
                    SCNS -> SCNS: validateScenario(scenario)
                    activate SCNS
                        SCNS --> SCNS: true
                        deactivate SCNS
                    SCNS --> SCNS: true
                    deactivate SCNS

                SCNS --> MAP: success
                deactivate SCNS

            MAP --> MAPS: success
            deactivate MAP

            MAPS --> MAP_REPO: success
            deactivate MAPS

            MAP_REPO --> CTRL: success
            deactivate MAP_REPO

    end

    autonumber 23
    <-- CTRL : success
deactivate CTRL


@enduml