@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateScenarioController" as CTRL
participant "map\n:Map" as MAP

autonumber 25
-> CTRL : getMapCities(selectedMap)

autonumber 25.1
activate CTRL
    group Get Map Cities List
        CTRL -> MAP : getCities()
        activate MAP
            MAP --> CTRL : cityList
        deactivate MAP
    end

    autonumber 26
    <-- CTRL : cityList
deactivate CTRL

@enduml 