@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "map\n:Map" as MAP
participant "scenario\n:Scenario" as SCENARIO

autonumber 38
-> MAP : createScenario(nameID, editor, startDate, endDate,\n selectedIndustries, portImports, portExports, portProduces,\n genIndustryFactors, availableLocomotives, mapCityList, cityTrafficRates)

autonumber 38.1
activate MAP
    group Create Scenario
        MAP --> SCENARIO** : create(nameID, editor, startDate, endDate,\n selectedIndustries, availableLocomotives, mapCityList)

        loop for each port in selectedIndustries
            MAP -> SCENARIO : configurePort(port, portImports, portExports, portProduces)
            activate SCENARIO
                SCENARIO --> MAP : true
            deactivate SCENARIO
        end

        loop for each generating industry in selectedIndustries
            MAP -> SCENARIO : configureGeneratingIndustry(industry, genIndustryFactors)
            activate SCENARIO
                SCENARIO --> MAP : true
            deactivate SCENARIO
        end

        loop for each city in mapCityList
            MAP -> SCENARIO : configureCity(city, cityTrafficRates)
            activate SCENARIO
                SCENARIO --> MAP : true
            deactivate SCENARIO
        end

        MAP -> MAP : addScenario(scenario)
        activate MAP
            MAP -> MAP : validateScenario()
            activate MAP
                MAP --> MAP : true
            deactivate MAP
            MAP --> MAP : true
        deactivate MAP
    end

    autonumber 39
    <-- MAP : scenario
deactivate MAP

@enduml 