@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateScenarioController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "mapDTO\n:MapDTO" as MAP_DTO
participant "mapRepository\n:MapRepository" as MAP_REPO
participant ":ScenarioMapper" as SCN_MAPPER
participant "scenarioDTO\n:ScenarioDTO" as SCN_DTO
participant "scenario:Scenario" as SCN
participant "map\n:Map" as MAP
participant "scenarios:Scenarios" as SCNS

autonumber 22
-> CTRL: createScenario(mapDTO, scenarioDTO)

autonumber 22.1
activate CTRL
    group Create Scenario Object

        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL: repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON: getMapRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL: mapRepository
        deactivate REPOS_SINGLETON

        CTRL -> MAP_DTO: getListOfCityDTO()
        activate MAP_DTO

            MAP_DTO --> CTRL: listCityDTO
        deactivate MAP_DTO

        CTRL -> SCN_DTO: addCities(listCityDTO)
        activate SCN_DTO
            deactivate SCN_DTO


        CTRL -> CTRL: getEditorFromSession()
        activate CTRL

        ref over CTRL
            Get EditorDTO
        end ref

        CTRL --> CTRL: editorDTO
        deactivate CTRL

        CTRL -> SCN_DTO: addEditor(editorDTO)
        activate SCN_DTO
            deactivate SCN_DTO


        CTRL -> MAP_REPO: createScenario(scenarioDTO)
            activate MAP_REPO

            MAP_REPO -> SCN_MAPPER: scenario = toModel(scenarioDTO)
                activate SCN_MAPPER

                SCN_MAPPER -> SCN_DTO: nameID = getNameID()
                activate SCN_DTO
                deactivate SCN_DTO

                ' Conversão do Editor
                SCN_MAPPER -> SCN_DTO: editorDTO = getEditor()
                activate SCN_DTO
                deactivate SCN_DTO
                SCN_MAPPER -> SCN_MAPPER: editor = toEditorModel(editorDTO)
                activate SCN_MAPPER
                deactivate SCN_MAPPER

                SCN_MAPPER -> SCN_DTO: startDate = getStartDate()
                activate SCN_DTO
                deactivate SCN_DTO

                SCN_MAPPER -> SCN_DTO: endDate = getEndDate()
                activate SCN_DTO
                deactivate SCN_DTO

                SCN_MAPPER -> SCN_DTO: initialBudget = getInitialBudget()
                activate SCN_DTO
                deactivate SCN_DTO

                ' Conversão das Industries
                SCN_MAPPER -> SCN_DTO: industriesDTO = getIndustries()
                activate SCN_DTO
                deactivate SCN_DTO
                SCN_MAPPER -> SCN_MAPPER: industries = toIndustryModels(industriesDTO)
                activate SCN_MAPPER
                deactivate SCN_MAPPER

                ' Conversão das Cities
                SCN_MAPPER -> SCN_DTO: citiesDTO = getCities()
                activate SCN_DTO
                deactivate SCN_DTO
                SCN_MAPPER -> SCN_MAPPER: cities = toCityModels(citiesDTO)
                activate SCN_MAPPER
                deactivate SCN_MAPPER

                ' Conversão dos LocomotiveTypes
                SCN_MAPPER -> SCN_DTO: locomotiveTypesDTO = getLocomotiveTypes()
                activate SCN_DTO
                deactivate SCN_DTO
                SCN_MAPPER -> SCN_MAPPER: locomotiveTypes = toLocomotiveTypeModels(locomotiveTypesDTO)
                activate SCN_MAPPER
                deactivate SCN_MAPPER

                SCN_MAPPER -> SCN**: create(nameID, editor, startDate, endDate, initialBudget,\nindustries, cities, locomotiveTypes)

            SCN_MAPPER --> MAP_REPO: scenario
            deactivate SCN_MAPPER

            MAP_REPO --> CTRL: scenario
            deactivate MAP_REPO

            CTRL -> MAP_REPO: saveScenario(scenario, mapDTO.getNameID())
            activate MAP_REPO

                MAP_REPO -> MAP_REPO: getMapByID(nameID)
                activate MAP_REPO
                    MAP_REPO --> MAP_REPO: map
                    deactivate MAP_REPO

                MAP_REPO -> MAP: map.addScenario(scenario)
                activate MAP
                    MAP -> SCNS: addScenario(scenario)
                    activate SCNS
                        deactivate SCNS

                deactivate MAP


                MAP_REPO -> MAP_REPO: save(map)
                activate MAP_REPO

                MAP_REPO --> MAP_REPO: success
                deactivate MAP_REPO

            MAP_REPO --> CTRL: success
            deactivate MAP_REPO

    end

    autonumber 23
    <-- CTRL : success
deactivate CTRL


@enduml