@startuml
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

title System Sequence Diagram: US04 - Create a Scenario

actor "Editor" as Editor
participant ":System" as System

activate Editor

    Editor -> System : asks to create a scenario
    activate System

        System --> Editor : requests name, start and end date (time period)
    deactivate System

        hnote right
            time restrictions
        end note

    Editor -> System : types requested data
    activate System

        System --> Editor : shows a list of industries and asks to select the ones available in the scenario
    deactivate System

            hnote right
                technological restrictions
            end note

    Editor -> System : selects the available industries in the scenario
    activate System


    loop while port exist (mixed industries)
            System --> Editor : shows a list of cargoes and asks to select the ones the port import
        deactivate System

        Editor -> System : selects the cargoes the port import
        activate System

            System --> Editor : shows a list of cargoes and asks to select the ones the port export
        deactivate System

            Editor -> System : selects the cargoes the port export
            activate System

            System --> Editor : shows a list of cargoes and asks to select the ones the port transform
        deactivate System

            Editor -> System : selects the cargoes the port transform
            activate System
    end

    hnote right
        historical restrictions
    end note

    loop while generating entities exist
            System --> Editor : requests the entities generating frequency factor
        deactivate System

        Editor -> System : types the generating entities factor
        activate System
    end

    hnote right
        historical restrictions
    end note

            System --> Editor : shows a list of locomotive types and asks to select the available ones
        deactivate System

            hnote right
                technological restrictions
            end note

        Editor -> System : selects the available locomotive types
        activate System

        System --> Editor : shows all data and requests confirmation
    deactivate System

    Editor -> System : confirms data
    activate System

        System --> Editor : displays operation success
    deactivate System

@enduml