@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

title System Sequence Diagram : US07 - Get Stations

participant ListStationController
participant ApplicationSession
participant Map
participant City
autonumber
activate ListStationController

autonumber 10
--> ListStationController: loadMap(mapId)

group GetStations
autonumber 10.1
  ListStationController -> ApplicationSession : getInstance()
  activate ApplicationSession
  ApplicationSession --> ListStationController : sessionInstance
  deactivate ApplicationSession

  ListStationController -> ApplicationSession : getCurrentMap()
  activate ApplicationSession
  ApplicationSession --> ListStationController : currentMap
  deactivate ApplicationSession

  ListStationController -> Map : getCities()
  activate Map
  Map --> ListStationController : citiesList
  deactivate Map

  loop for each city in citiesList
    ListStationController -> City : getStations()
    activate City
    City --> ListStationController : cityStations
    deactivate City
  end

  ListStationController --> ListStationController : compileStationsList()
end
autonumber 11
<-- ListStationController: stationsList
deactivate ListStationController

@enduml 