@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

title System Sequence Diagram : US07 - Get Station Details

participant ListStationController
participant Station

activate ListStationController

autonumber 7
--> ListStationController: getStationDetails(listStationsDTO, stationId)
group Get station details
    autonumber 7.1
    loop for each station in listStations
        ListStationController -> Station: getId()
        activate Station
        Station --> ListStationController: id
        deactivate Station

        alt if stationId.equals(id)
            ListStationController -> Station : getDetails()
              activate Station
              Station --> ListStationController : stationBasicInfo
              deactivate Station

              ListStationController -> Station : getBuildings()
              activate Station
              Station --> ListStationController : buildingsList
              deactivate Station

              ListStationController -> Station : getDemandedCargo()
              activate Station
              Station --> ListStationController : demandedCargoList
              deactivate Station

              ListStationController -> Station : getSupplyCargo()
              activate Station
              Station --> ListStationController : supplyCargoList
              deactivate Station

              ListStationController -> ListStationController : compileStationDetails()

            break
        end
    end
end

autonumber 8

<-- ListStationController: stationDetails

deactivate ListStationController

@enduml 