@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":ListStationController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "mapRepository\n:MapRepository" as MAP_REPO
participant "maps\n:Map" as MAPS
participant "map\n:Map" as MAP
participant "city\n:City" as CITY
participant "listStation\n:List<Station>" as listStation

participant ":StationMapper" as STATION_MAPPER
participant ":List<Station>" as STATION_LIST
participant ":List<StationDTO>" as STATION_LIST_DTO
participant "stationDTO\n:StationDTO" as STATION_DTO

autonumber 2
-> CTRL: getStationsDTO(mapID)

autonumber 2.1
activate CTRL
    group Get StationDTO List

        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL: repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON: getMapRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL: mapRepository
        deactivate REPOS_SINGLETON

        CTRL -> MAP_REPO: getMap(mapID)
        activate MAP_REPO
            MAP_REPO -> MAPS: getMap(mapID)
            activate MAPS

                MAPS --> MAP_REPO : map
            deactivate MAPS
            MAP_REPO --> CTRL: map
        deactivate MAP_REPO

        CTRL -> MAP: getCities()

        activate MAP
        MAP --> CTRL: cities
        deactivate MAP


        CTRL -> listStation : new ArrayList<>()

        loop for each city in cities
            CTRL -> CITY: getStations()
            activate CITY
                CITY --> CTRL: listStationsPerCity
            deactivate CITY
                CTRL -> listStation: add(listStationsPerCity))
        end

        listStation -> CTRL: listStation
        deactivate MAP

        CTRL -> STATION_MAPPER: toDTO(listStation)
                activate STATION_MAPPER

                    STATION_MAPPER --> STATION_LIST_DTO**: create()

                    loop for each object in listStation
                        STATION_MAPPER -> STATION_LIST: stationType = get(i)
                        activate STATION_LIST
                            deactivate STATION_LIST

                        STATION_MAPPER -> STATION_MAPPER: stationDTO = toDTO(station)
                        activate STATION_MAPPER
                            STATION_MAPPER --> STATION_DTO**: create()
                            deactivate STATION_MAPPER

                        STATION_MAPPER -> STATION_LIST_DTO: add(stationDTO)
                        activate STATION_LIST_DTO
                            deactivate STATION_LIST_DTO
                    end

                    STATION_MAPPER --> CTRL: listStationDTO
                deactivate STATION_MAPPER

    end
    autonumber 3
        <--CTRL : listStationDTO


@enduml 