@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

title System Sequence Diagram : US07 - List stations and view details

actor "Player" as Player
participant ListStationUI
participant ListStationController




activate Player


note left of ListStationUI
    Retrieves available maps and scenarios and loads them
end note

Player -> ListStationUI : request to see available stations
        activate ListStationUI
        ListStationUI --> ListStationController: getStationsDTO(mapId)
        activate ListStationController
        
        ref over ListStationController
        Get available stations
        end
        
        ListStationController --> ListStationUI: stationsDTOList
        deactivate ListStationController
        
        ListStationUI --> Player : displays list of available stations
        ListStationUI --> Player : requests to select a specific station
        deactivate ListStationUI

Player -> ListStationUI : selects a specific station
        activate ListStationUI
        ListStationUI --> ListStationController: getStationDetails(listStation, stationId)
        activate ListStationController
        
        ref over ListStationController
        Get station details
        end
        
        ListStationController --> ListStationUI: stationDetails
        deactivate ListStationController
        
        ListStationUI --> Player : show station details
        deactivate ListStationUI

@enduml 