@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Editor" as EDITOR
participant ":system" as SYSTEM

activate EDITOR

    EDITOR -> SYSTEM : asks to add an industry
    activate SYSTEM
        SYSTEM --> EDITOR : shows a list of available maps
    deactivate SYSTEM

    EDITOR -> SYSTEM : selects a map
    activate SYSTEM
        SYSTEM --> EDITOR : displays the selected map
    deactivate SYSTEM

    EDITOR -> SYSTEM : confirms the selected map
    activate SYSTEM
        SYSTEM --> EDITOR : shows a list of industry sectors
    deactivate SYSTEM

    EDITOR -> SYSTEM : selects an industry sector
    activate SYSTEM
        SYSTEM --> EDITOR : asks for industry data
    deactivate SYSTEM

    EDITOR -> SYSTEM : provides industry data
    activate SYSTEM
        SYSTEM --> EDITOR : shows industry data and asks for confirmation
    deactivate SYSTEM

    EDITOR -> SYSTEM : confirms the data
    activate SYSTEM
        SYSTEM --> EDITOR : displays success message
    deactivate SYSTEM

deactivate EDITOR
@enduml