@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

class SaveScenarioUI {
}

class SaveScenarioController {
    + saveScenario()
}

class Scenario {
    + serialize()
}

class ScenarioRepository {
    + saveScenario(serializedScenarioData)
}

SaveScenarioUI --> SaveScenarioController
SaveScenarioController --> Scenario
SaveScenarioController --> ScenarioRepository

@enduml 