@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Player" as PLAYER
participant ":BuyLocomotiveUI" as UI
participant ":BuyLocomotiveController" as CTRL

activate PLAYER

    PLAYER -> UI : asks to buy a locomotive
    activate UI
        UI --> CTRL** : create()
        UI -> CTRL : getAvailableLocomotives()

        ref over CTRL
            Get Available LocomotiveDTO List
        end ref

        activate CTRL
            CTRL --> UI : listAvailableLocomotiveDTO
        deactivate CTRL

        UI --> PLAYER : shows a list of available locomotives\n (for the scenario and current date)
    deactivate UI

    PLAYER -> UI : selects a locomotive
    activate UI
        UI -> CTRL : getLocomotive(locomotiveDTO)
        
        ref over CTRL
            Get LocomotiveDTO
        end ref

        activate CTRL
            CTRL --> UI : locomotiveDTO
        deactivate CTRL

        UI --> PLAYER : shows locomotive details and requests confirmation
    deactivate UI

    PLAYER -> UI : confirms purchase
    activate UI
        UI -> CTRL : purchaseLocomotive(locomotiveDTO)

        ref over CTRL
            Purchase Locomotive
        end ref

        activate CTRL
            CTRL --> UI : success
        deactivate CTRL

        UI --> PLAYER : displays operation success
    deactivate UI

deactivate PLAYER

@enduml
