@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":BuyLocomotiveController" as CTRL
participant "currentSession\n:UserSession" as CURRENT_SESSION
participant "locomotiveDTO\n:LocomotiveDTO" as LOC_DTO
participant "locomotiveRepository\n:LocomotiveRepository" as LOC_REPO
participant "locomotives\n:Locomotives" as LOCS
participant "locomotive\n:Locomotive" as LOC
participant "scenario\n:Scenario" as SCN
participant "players\n:Players" as PLYS
participant "player\n:Player" as PLAYER
participant "playerLocomotives\n:PlayerLocomotives" as PLAYER_LOCS

autonumber 5
-> CTRL: purchaseLocomotive(locomotiveDTO)

autonumber 5.1
activate CTRL
    group Purchase Locomotive

        CTRL -> CURRENT_SESSION: getCurrentScenario()
        activate CURRENT_SESSION
            CURRENT_SESSION --> CTRL: scenario
        deactivate CURRENT_SESSION

        CTRL -> CURRENT_SESSION: getCurrentPlayer()
        activate CURRENT_SESSION
            CURRENT_SESSION --> CTRL: player
        deactivate CURRENT_SESSION

        CTRL -> LOC_DTO: getNameID()
        activate LOC_DTO
            LOC_DTO --> CTRL: locomotiveNameID
        deactivate LOC_DTO

        CTRL -> LOC_REPO: getLocomotive(locomotiveNameID)
        activate LOC_REPO
            LOC_REPO -> LOCS: getLocomotive(locomotiveNameID)
            activate LOCS
                LOCS --> LOC_REPO: locomotive
            deactivate LOCS
            LOC_REPO --> CTRL: locomotive
        deactivate LOC_REPO

        CTRL -> LOC_REPO: purchaseLocomotive(locomotive, player, scenario)
        activate LOC_REPO
            LOC_REPO -> LOCS: purchaseLocomotive(locomotive, player, scenario)
            activate LOCS
                LOCS -> LOC: purchaseLocomotive(player, scenario)
                activate LOC
                    LOC -> LOC: getPrice()
                    activate LOC
                        LOC --> LOC: price
                    deactivate LOC

                    LOC -> SCN: hasSufficientFunds(price, player, scenario)
                    activate SCN

                        SCN -> PLYS: hasSufficientFunds(price, player)
                        activate PLYS

                            PLYS -> PLAYER: hasSufficientFunds(price)
                            activate PLAYER

                            PLAYER --> PLYS: true
                            deactivate PLAYER

                        PLYS --> SCN: true
                    deactivate PLYS

                    SCN --> LOC: true
                    deactivate SCN

                    LOC -> SCN: addLocomotive(price, locomotive, player, scenario)
                    activate SCN
                        SCN -> PLYS: addLocomotive(price, locomotive, player)
                        activate PLYS

                            PLYS -> PLAYER: addLocomotive(price, locomotive)
                            activate PLAYER

                            PLAYER -> PLAYER: removeBudget(price)
                            activate PLAYER
                            PLAYER --> PLAYER: true
                            deactivate PLAYER

                            PLAYER -> PLAYER_LOCS: addLocomotive(locomotive)
                            activate PLAYER_LOCS
                                deactivate PLAYER_LOCS

                            PLAYER --> PLYS: success
                            deactivate PLAYER

                            PLYS --> SCN: success
                            deactivate PLYS

                        SCN --> LOC: success
                    deactivate SCN

                    LOC --> LOCS: success
                deactivate LOC
                LOCS --> LOC_REPO: success
            deactivate LOCS
            LOC_REPO --> CTRL: success
        deactivate LOC_REPO

    end

    autonumber 6
    <-- CTRL : success
deactivate CTRL

@enduml
