@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":BuyLocomotiveController" as CTRL
participant "locomotive\n:Locomotive" as LOCOMOTIVE
participant "player\n:Player" as PLAYER_OBJ

autonumber 24.14
-> CTRL : purchaseLocomotive(locomotive)

autonumber 24.15
activate CTRL
    group Purchase Locomotive
        CTRL -> LOCOMOTIVE : getPrice()
        activate LOCOMOTIVE
            LOCOMOTIVE --> CTRL : locomotivePrice
        deactivate LOCOMOTIVE

        CTRL -> CTRL : checkBalance(locomotivePrice, player)
        activate CTRL
            CTRL -> PLAYER_OBJ : hasSufficientMoney(locomotivePrice)
            activate PLAYER_OBJ
                PLAYER_OBJ --> CTRL : true
            deactivate PLAYER_OBJ
            CTRL --> CTRL : true
        deactivate CTRL

        CTRL -> PLAYER_OBJ : completePurchase(locomotive)
        activate PLAYER_OBJ
            PLAYER_OBJ -> PLAYER_OBJ : removeMoney(locomotivePrice)
            activate PLAYER_OBJ
                PLAYER_OBJ --> PLAYER_OBJ : true
            deactivate PLAYER_OBJ

            PLAYER_OBJ -> PLAYER_OBJ : addLocomotive(locomotive)
            activate PLAYER_OBJ
                PLAYER_OBJ --> PLAYER_OBJ : true
            deactivate PLAYER_OBJ

            PLAYER_OBJ --> CTRL : true
        deactivate PLAYER_OBJ

        CTRL -> LOCOMOTIVE : setOwner(player)
        activate LOCOMOTIVE
            LOCOMOTIVE --> CTRL : true
        deactivate LOCOMOTIVE
    end

    autonumber 25
    <-- CTRL : true
deactivate CTRL

@enduml 