@startuml
skinparam packageStyle rectangle
skinparam shadowing false

participant ":StationBuildingController" as CTRL
participant "map\n:Map" as MAP

autonumber 21
-> CTRL : getClosestCity(position)

autonumber 21.1
activate CTRL
    group Get Closest City
        ' Get closest city
        CTRL -> MAP : getClosestCity(position)
        activate MAP
            MAP --> CTRL : closestCity
        deactivate MAP
    end

    autonumber 22
    <-- CTRL : closestCity
deactivate CTRL

@enduml 