@startuml
skinparam packageStyle rectangle
skinparam shadowing false

participant ":StationBuildingController" as CTRL
participant "ApplicationSession" as APP_SESSION
participant "appSession\n:ApplicationSession" as APP_SESSION_SINGLETON
participant "mapRepository\n:MapRepository" as MAP_REPO
participant "map\n:Map" as MAP

autonumber 7
-> CTRL : loadMap(nameID)

autonumber 7.1
activate CTRL
    group Load Selected Map
        CTRL -> APP_SESSION: getInstance()
        activate APP_SESSION
            APP_SESSION --> CTRL: appSession
        deactivate APP_SESSION

        CTRL -> APP_SESSION_SINGLETON: setCurrentMap(nameID)
        activate APP_SESSION_SINGLETON
            APP_SESSION_SINGLETON --> CTRL: success
        deactivate APP_SESSION_SINGLETON

        CTRL -> MAP_REPO: getMapByID(nameID)
        activate MAP_REPO
            MAP_REPO --> CTRL: map
        deactivate MAP_REPO

        CTRL -> MAP: getMapLayout()
        activate MAP
            MAP --> CTRL: mapLayout
        deactivate MAP
    end

    autonumber 8
    <-- CTRL : mapLayout
deactivate CTRL

@enduml 