@startuml
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

title Sequence Diagram: US05 - Build a Station (Split)

actor "Player" as PLAYER
participant ":StationBuildingUI" as UI
participant ":StationBuildingController" as CTRL


activate PLAYER

    PLAYER -> UI : asks to see available maps
    activate UI
        UI --> CTRL** : create()
        UI -> CTRL : getAvailableMaps()
        
        ref over CTRL
            Get Available Maps List
        end ref
        
        activate CTRL
            CTRL --> UI : availableMapsList
        deactivate CTRL
        
        UI --> PLAYER : shows list of available maps
    deactivate UI

    PLAYER -> UI : selects a map
    activate UI
        UI -> CTRL : loadMap(nameID)
        
        ref over CTRL
            Load Selected Map
        end ref
        
        activate CTRL
            CTRL --> UI : mapLayout
        deactivate CTRL
        
        UI --> PLAYER : loads and displays the selected map
    deactivate UI

    PLAYER -> UI : asks to build a station
    activate UI
        UI -> CTRL : getStationTypes()
        
        ref over CTRL
            Get Station Types List
        end ref
        
        activate CTRL
            CTRL --> UI : stationTypeList
        deactivate CTRL
        
        UI --> PLAYER : requests station type (DEPOT, STATION, TERMINAL)
    deactivate UI

    PLAYER -> UI : selects station type
    activate UI
        UI --> PLAYER : requests location (Position) on map for the station
    deactivate UI

    PLAYER -> UI : provides location coordinates
    activate UI
        UI -> CTRL : validatePosition(position)
        
        ref over CTRL
            Validate Position
        end ref
        
        activate CTRL
            CTRL --> UI : valid
        deactivate CTRL

        alt stationType.name == "STATION"
            UI --> PLAYER : requests center point selection (NE, SE, NW, SW)
            deactivate UI

            PLAYER -> UI : selects center point
            activate UI
        end

        UI -> CTRL : getClosestCity(position)
        
        ref over CTRL
            Get Closest City
        end ref
        
        activate CTRL
            CTRL --> UI : closestCity
        deactivate CTRL
        
        UI -> CTRL : previewStationPlacement(stationType, position, centerPoint)
        
        ref over CTRL
            Preview Station Placement
        end ref
        
        activate CTRL
            CTRL --> UI : preview, economicRadius, cost
        deactivate CTRL

        UI --> PLAYER : proposes station name based on closest city
        UI --> PLAYER : displays station cost and economic radius
        UI --> PLAYER : shows preview of station placement and requests confirmation
    deactivate UI

    PLAYER -> UI : confirms station placement
    activate UI
        UI -> CTRL : buildStation(stationType, position, centerPoint)
        
        ref over CTRL
            Build Station
        end ref
        
        activate CTRL
            CTRL --> UI : success
        deactivate CTRL

        UI --> PLAYER : displays operation success
        UI --> PLAYER : updates map with the new station
    deactivate UI

deactivate PLAYER

@enduml 