@startuml
skinparam packageStyle rectangle
skinparam shadowing false

participant ":StationBuildingController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "stationTypeRepository\n:StationTypeRepository" as ST_TYPE_REPO

autonumber 11
-> CTRL : getStationTypes()

autonumber 11.1
activate CTRL
    group Get Station Types List
        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL: repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON : getStationTypeRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL: stationTypeRepository
        deactivate REPOS_SINGLETON

        CTRL -> ST_TYPE_REPO : getStationTypes()
        activate ST_TYPE_REPO
            ST_TYPE_REPO --> CTRL : stationTypeList
        deactivate ST_TYPE_REPO
    end

    autonumber 12
    <-- CTRL : stationTypeList
deactivate CTRL

@enduml 