@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":BuildStationController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "mapRepository\n:MapRepository" as REPOS_MAP

autonumber 8
-> CTRL: getMapPositions()
    activate CTRL
    autonumber 8.1
    group Get available map positions
        CTRL -> REPOS: getInstance()
        activate REPOS
            REPOS --> CTRL: repositories
        deactivate REPOS
        
        CTRL -> REPOS_SINGLETON: getMapRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL: mapRepository
        deactivate REPOS_SINGLETON
        
        CTRL -> REPOS_MAP: getAvailablePositions()
        activate REPOS_MAP
            REPOS_MAP --> CTRL: availablePositions
        deactivate REPOS_MAP
    end
    autonumber 9
    <-- CTRL: availablePositions
deactivate CTRL

@enduml 