@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":BuildStationController" as CTRL
participant "ApplicationSession" as APP_SESSION
participant "appSession\n:ApplicationSession" as APP_SESSION_SINGLETON
participant "player\n:Player" as PLAYER

autonumber 13
-> CTRL: validateBudget(stationType)
    activate CTRL
    autonumber 13.1
    group Validate player budget
        CTRL -> APP_SESSION: getInstance()
        activate APP_SESSION
            APP_SESSION --> CTRL: appSession
        deactivate APP_SESSION
        
        CTRL -> APP_SESSION_SINGLETON: getCurrentSession()
        activate APP_SESSION_SINGLETON
            APP_SESSION_SINGLETON --> CTRL: player
        deactivate APP_SESSION_SINGLETON
        
        CTRL -> PLAYER: validateBudget(stationType.getCost())
        activate PLAYER
            PLAYER --> CTRL: valid
        deactivate PLAYER
    end
    autonumber 14
    <-- CTRL: valid
deactivate CTRL

@enduml 