@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":BuildStationController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "mapRepository\n:MapRepository" as REPOS_MAP
participant "map\n:Map" as MAP

autonumber 11
-> CTRL: validatePosition(position)
    activate CTRL
    autonumber 11.1
    group Validate position
        CTRL -> REPOS: getInstance()
        activate REPOS
            REPOS --> CTRL: repositories
        deactivate REPOS
        
        CTRL -> REPOS_SINGLETON: getMapRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL: mapRepository
        deactivate REPOS_SINGLETON
        
        CTRL -> REPOS_MAP: getMapByID(currentMapID)
        activate REPOS_MAP
            REPOS_MAP --> CTRL: map
        deactivate REPOS_MAP
        
        CTRL -> MAP: validatePosition(position)
        activate MAP
            MAP --> CTRL: valid
        deactivate MAP
    end
    autonumber 12
    <-- CTRL: valid
deactivate CTRL

@enduml 