@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

title System Sequence Diagram: US06 - Upgrade a selected station with a building

actor "Player" as player
participant ":System" as system

activate player
player -> system: asks to see available maps
activate system
system --> player: shows list of available maps to play
deactivate system
player -> system: selects a map
activate system
system --> player: shows list of available scenarios to play
deactivate system
player -> system : selects a scenario
activate system

system --> player: loads and displays the selected map
deactivate system

player -> system: requests to see available stations
activate system
system --> player: displays list of available stations
deactivate system

player -> system: selects a specific station
activate system
system --> player: shows station details
deactivate system
player -> system: asks to upgrade station
activate system
system --> player: shows list of available buildings for upgrading
deactivate system

player -> system: selects building
activate system
system --> player: displays building information
system --> player: asks for confirmation
deactivate system

player -> system: confirms upgrade
activate system
system --> player: displays operation success
system --> player: displays station and building new information
deactivate system

deactivate player
@enduml