@startuml
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Product Owner" as PO
participant ":SimulatorUI" as UI
participant ":SimulatorController" as CTRL
participant ":Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "simulatorRepository\n:SimulatorRepository" as SIM_REPO
participant "mapRepository\n:MapRepository" as MAP_REPO
participant "scenarioRepository\n:ScenarioRepository" as SCENARIO_REPO
participant "simulator\n:Simulator" as SIM

activate PO

    PO -> UI : asks to start a simulation
    activate UI
        UI --> CTRL** : create()

        UI -> CTRL : getAvailableMaps()
        activate CTRL
            CTRL -> REPOS : getInstance()
            activate REPOS
                REPOS --> CTRL: repositories
            deactivate REPOS

            CTRL -> REPOS_SINGLETON : getMapRepository()
            activate REPOS_SINGLETON
                REPOS_SINGLETON --> CTRL: mapRepository
            deactivate REPOS_SINGLETON

            CTRL -> MAP_REPO : getAllMaps()
            activate MAP_REPO
                MAP_REPO --> CTRL : mapList
            deactivate MAP_REPO

            CTRL --> UI : mapList
        deactivate CTRL

        UI -> CTRL : getAvailableScenarios()
        activate CTRL
            CTRL -> REPOS : getInstance()
            activate REPOS
                REPOS --> CTRL: repositories
            deactivate REPOS

            CTRL -> REPOS_SINGLETON : getScenarioRepository()
            activate REPOS_SINGLETON
                REPOS_SINGLETON --> CTRL: scenarioRepository
            deactivate REPOS_SINGLETON

            CTRL -> SCENARIO_REPO : getAllScenarios()
            activate SCENARIO_REPO
                SCENARIO_REPO --> CTRL : scenarioList
            deactivate SCENARIO_REPO

            CTRL --> UI : scenarioList
        deactivate CTRL

        UI --> PO : shows details (map and scenario for the simulation) and asks confirmation
    deactivate UI

    PO -> UI : confirms simulation
    activate UI
        UI -> CTRL : startSimulation(selectedMap, selectedScenario)
        activate CTRL
            CTRL -> REPOS : getInstance()
            activate REPOS
                REPOS --> CTRL: repositories
            deactivate REPOS

            CTRL -> REPOS_SINGLETON : getSimulatorRepository()
            activate REPOS_SINGLETON
                REPOS_SINGLETON --> CTRL: simulatorRepository
            deactivate REPOS_SINGLETON

            CTRL -> SIM_REPO : createSimulator(selectedMap, selectedScenario)
            activate SIM_REPO
                SIM_REPO --> SIM** : create(selectedMap, selectedScenario)
                SIM_REPO --> CTRL : simulator
            deactivate SIM_REPO

            CTRL -> SIM : start()
            activate SIM
                SIM --> CTRL : true
            deactivate SIM

            CTRL --> UI : success
        deactivate CTRL

        UI --> PO : display operation success (simulation started)
    deactivate UI

    loop while simulation is running
        alt user requests operation
            PO -> UI : asks for operation (buy locomotive, add railway line, etc.)
            activate UI
                UI -> CTRL : getOperationDetails(operationType)
                activate CTRL
                    CTRL -> SIM : getOperationDetails(operationType)
                    activate SIM
                        SIM --> CTRL : operationDetails
                    deactivate SIM
                    CTRL --> UI : operationDetails
                deactivate CTRL
                UI --> PO : shows operation details and ask confirmation
            deactivate UI

            PO -> UI : confirms operation
            activate UI
                UI -> CTRL : executeOperation(operationType, parameters)
                activate CTRL
                    CTRL -> SIM : executeOperation(operationType, parameters)
                    activate SIM
                        SIM --> CTRL : result
                    deactivate SIM
                    CTRL --> UI : result
                deactivate CTRL
                UI --> PO : displays operation success
            deactivate UI

        else user pauses simulation
            PO -> UI : asks to pause the simulator
            activate UI
                UI -> CTRL : pauseSimulation()
                activate CTRL
                    CTRL -> SIM : pause()
                    activate SIM
                        SIM --> CTRL : success
                    deactivate SIM
                    CTRL --> UI : success
                deactivate CTRL
                UI --> PO : pauses simulation and waits for instructions to resume
            deactivate UI

            PO -> UI : asks to resume the simulation
            activate UI
                UI -> CTRL : resumeSimulation()
                activate CTRL
                    CTRL -> SIM : resume()
                    activate SIM
                        SIM --> CTRL : success
                    deactivate SIM
                    CTRL --> UI : success
                deactivate CTRL
                UI --> PO : resume simulation of the map and scenario
            deactivate UI

        else user stops simulation
            PO -> UI : asks to stop the simulation
            activate UI
                UI --> PO : requests confirmation
            deactivate UI

            PO -> UI : confirms end of simulation
            activate UI
                UI -> CTRL : stopSimulation()
                activate CTRL
                    CTRL -> SIM : stop()
                    activate SIM
                        SIM -> SIM : generateReport()
                        SIM --> CTRL : simulationReport
                    deactivate SIM
                    CTRL --> UI : simulationReport
                deactivate CTRL
                UI --> PO : shows simulation results and creates a report
            deactivate UI
        end
    end

deactivate PO

@enduml 