@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":SimulatorController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "scenarioRepository\n:ScenarioRepository" as SCENARIO_REPO

autonumber 5
-> CTRL : getAvailableScenarios()

autonumber 5.1
activate CTRL
    group Get Available Scenarios
        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL: repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON : getScenarioRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL: scenarioRepository
        deactivate REPOS_SINGLETON

        CTRL -> SCENARIO_REPO : getAllScenarios()
        activate SCENARIO_REPO
            SCENARIO_REPO --> CTRL : scenarioList
        deactivate SCENARIO_REPO
    end

    autonumber 6
    <-- CTRL : scenarioList
deactivate CTRL

@enduml 