@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam class {
  BackgroundColor LightBlue
  BorderColor Blue
}
skinparam enum {
  BackgroundColor LightBlue
  BorderColor Blue
}
hide circle
hide methods

title Domain Model Excerpt: US09 - Buy a Locomotive

class Player {
  username
  password
}

class Map {
  nameID
  scale
}

class Scenario {
  nameID
  startDate
  endDate
  initialBudget
  currentBudget
}

class Locomotive {
  nameID
  owner
  type
  power
  acceleration
  topSpeed
  actualSpeed
  startYear
  fuelAcquisitionPrice
  fuelConsumptionPrice
  availabilityYear
  acquisitionPrice
  baseMaintenanceCost
  maintenanceFrequency
  wearAndTearFactor
}

Player "1" -- "*" Scenario : plays >
Player "1" -- "*" Locomotive : buys >
Scenario "1" -- "*" Locomotive : configures >
Scenario "*" -- "1" Map : uses >
Map "1" -- "*" Scenario : contains >

@enduml