@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Player" as Player
participant ":System" as System

activate Player

    Player -> System : asks to check lines maintenance route
    activate System

        System --> Player : shows maintenance type options and asks to select one\n(all lines or only electrified lines)
    deactivate System

    Player -> System : selects maintenance type
    activate System

        System --> Player : loads and displays the railway network visualization
    deactivate System

    Player -> System : requests maintenance route calculation
    activate System

        System --> Player : displays the maintenance route\n(passing once through each line)
    deactivate System

deactivate Player
@enduml
