@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

skinparam classAttributeIconSize 0

class CreateMapUI {
    + requestMapData()
    + showMapData()
    + requestConfirmation()
    + displaySuccess()
    + displayMapDetails()
}

class CreateMapController {
    + create()
    + createMap(mapDTO)
}

class Repositories {
    - Repositories()
    + {static} getInstance()
    + getMapRepository()
}

class MapRepository {
    + createMap(mapDTO)
}

class Maps {
    + createMap(mapDTO)
    + addMap(map)
    + validateMap(map)
}

class Map {
    - nameID : String
    - size : Size
    - scale : double
    + Map(nameID, size, scale)
}

class Size {
    - width : double
    - height : double
    + Size(width, height)
}

class MapDTO {
    - nameID : String
    - width : double
    - height : double
    - scale : double
    + getNameID()
    + getWidth()
    + getHeight()
    + getScale()
}

class MapMapper {
    + toModel(mapDTO)
    + toDTO(List<Map>)
    + toDTO(Map)
    + getNameID()
    + getWidth()
    + getHeight()
    + getScale()
    + createSize(width, height)
}

CreateMapUI "1" --> "1" CreateMapController
CreateMapController "1" --> "1" Repositories : repositories
CreateMapController "1" --> "1" MapDTO

Repositories "1" --> "1" MapRepository

MapRepository "1" --> "1" Maps : maps
Maps "1" --> "*" Map : maps

Map "1" --> "1" Size : size

MapDTO "1" --> "1" Size : size

MapMapper "1" --> "1" Map : maps
MapMapper "1" --> "1" MapDTO : maps to

MapRepository "1" --> "1" MapMapper : uses

@enduml
