@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

title Class Diagram: US01 - Create a Map

class CreateMapUI {
}

class CreateMapController {
    + create()
    + validateMapData(mapDTO: MapDTO) : boolean
    + createMap(mapDTO: MapDTO) : MapDTO
}

class MapDTO {
    + nameID : String
    + width : int
    + height : int
    + scale : int
}



    class Map {
        - nameID : String
        - size : Size
        - scale : int


        + {static} validateMapName(nameID) : boolean
        + createMap(nameID: String, size: Size) : Map
        + toDTO() : MapDTO
    }

class Size {
    - width : int
    - height : int

    + {static} validateSize(width: int, height: int) : boolean
    + createSize(width: int, height: int) : Size
}



    class MapRepository {
        + save(map: Map) : boolean
        + getMapByID(nameID: String) : Map
    }

    class Repositories {
        + {static} getInstance() : Repositories
        + getMapRepository() : MapRepository
    }

    class ApplicationSession {
        + {static} getInstance() : ApplicationSession
    }


CreateMapUI ..> CreateMapController
CreateMapController ..> MapDTO
CreateMapController ..> MapRepository
CreateMapController ..> Repositories
CreateMapController ..> ApplicationSession
CreateMapController ..> Map
CreateMapController ..> Size

Map "1" --> "1" Size : size
MapRepository --> "1" Map : map

Repositories -> "1" Repositories : instance
Repositories --> "1" MapRepository : mapRepository

ApplicationSession -> "1" ApplicationSession : instance

@enduml
